Repository koobiq/angular-components, pull requests merged in 2024-06, with the labels that each got.

#54 fix(icon-item): added warning color, fixed tokens after removal in design-tokens repo (#DS-2510)
  apps/docs/src/assets/stackblitz/package.json
  apps/docs/src/styles/koobiq/default-theme/_palette.scss
  apps/docs/src/styles/koobiq/default-theme/_variables.scss
  apps/docs/src/styles/koobiq/default-theme/index.d.ts
  apps/docs/src/styles/koobiq/default-theme/js/index.js
  package.json
  packages/components-dev/icon/template.html
  packages/components/core/option/_option-action-theme.scss
  packages/components/core/styles/theming/_components-theming.scss
  packages/components/core/styles/theming/_theming.scss
  packages/components/icon/_icon-item-theme.scss
  packages/components/icon/_icon-theme.scss
  packages/components/package.json
  yarn.lock
Labels: enhancement

#45 feat(docs): alert v2 documentation text (#DS-2343)
  apps/docs/src/assets/stackblitz/package.json
  apps/docs/src/styles/koobiq/default-theme/_variables.scss
  apps/docs/src/styles/koobiq/default-theme/css-tokens.css
  apps/docs/src/styles/koobiq/default-theme/index.d.ts
  apps/docs/src/styles/koobiq/default-theme/js/index.js
  package.json
  packages/components/alert/alert.component.scss
  packages/components/alert/alerts.md
  packages/components/package.json
  packages/docs-examples/components/alerts/alert-close/alert-close-example.css
  packages/docs-examples/components/alerts/alert-close/alert-close-example.html
  packages/docs-examples/components/alerts/alert-close/alert-close-example.ts
  packages/docs-examples/components/alerts/alert-content/alert-content-example.css
  packages/docs-examples/components/alerts/alert-content/alert-content-example.html
  packages/docs-examples/components/alerts/alert-content/alert-content-example.ts
  packages/docs-examples/components/alerts/alert-size/alert-size-example.css
  packages/docs-examples/components/alerts/alert-size/alert-size-example.html
  packages/docs-examples/components/alerts/alert-size/alert-size-example.ts
  packages/docs-examples/components/alerts/alert-status/alert-status-example.css
  packages/docs-examples/components/alerts/alert-status/alert-status-example.html
  packages/docs-examples/components/alerts/alert-status/alert-status-example.ts
  packages/docs-examples/components/alerts/alert-variants/alert-variants-example.css
  packages/docs-examples/components/alerts/alert-variants/alert-variants-example.html
  packages/docs-examples/components/alerts/alert-variants/alert-variants-example.ts
  packages/docs-examples/components/alerts/alerts-overview/alerts-overview-example.html
  packages/docs-examples/components/alerts/index.ts
  yarn.lock
Labels: documentation

#56 docs(toast): refine the artice and examples (#DS-2361)
  apps/docs/src/app/components/documentation-items.ts
  packages/components/toast/examples.toast.md
  packages/components/toast/toast.md
  packages/docs-examples/components/toast/index.ts
  packages/docs-examples/components/toast/toast-actions-overview/toast-actions-overview-example.css
  packages/docs-examples/components/toast/toast-actions-overview/toast-actions-overview-example.html
  packages/docs-examples/components/toast/toast-actions-overview/toast-actions-overview-example.ts
  packages/docs-examples/components/toast/toast-hide-overview/toast-hide-overview-example.css
  packages/docs-examples/components/toast/toast-hide-overview/toast-hide-overview-example.html
  packages/docs-examples/components/toast/toast-hide-overview/toast-hide-overview-example.ts
  packages/docs-examples/components/toast/toast-link-overview/toast-link-overview-example.css
  packages/docs-examples/components/toast/toast-link-overview/toast-link-overview-example.html
  packages/docs-examples/components/toast/toast-link-overview/toast-link-overview-example.ts
  packages/docs-examples/components/toast/toast-overview/toast-overview-example.html
  packages/docs-examples/components/toast/toast-overview/toast-overview-example.ts
  packages/docs-examples/components/toast/toast-progress-bar-overview/toast-progress-bar-overview-example.html
  packages/docs-examples/components/toast/toast-report-overview/toast-report-overview-example.css
  packages/docs-examples/components/toast/toast-report-overview/toast-report-overview-example.html
  packages/docs-examples/components/toast/toast-report-overview/toast-report-overview-example.ts
  packages/docs-examples/components/toast/toast-types-overview/toast-types-overview-example.css
  packages/docs-examples/components/toast/toast-types-overview/toast-types-overview-example.html
  packages/docs-examples/components/toast/toast-types-overview/toast-types-overview-example.ts
Labels: documentation

#49 docs(button-toggle): refine examples (DS-1567)
  packages/components/button-toggle/button-toggle.md
  packages/docs-examples/components/button-toggle/button-toggle-alignment-overview/button-toggle-alignment-overview-example.css
  packages/docs-examples/components/button-toggle/button-toggle-alignment-overview/button-toggle-alignment-overview-example.html
  packages/docs-examples/components/button-toggle/button-toggle-alignment-overview/button-toggle-alignment-overview-example.ts
  packages/docs-examples/components/button-toggle/button-toggle-disabled-all-overview/button-toggle-disabled-all-overview-example.css
  packages/docs-examples/components/button-toggle/button-toggle-disabled-all-overview/button-toggle-disabled-all-overview-example.html
  packages/docs-examples/components/button-toggle/button-toggle-disabled-all-overview/button-toggle-disabled-all-overview-example.ts
  packages/docs-examples/components/button-toggle/button-toggle-disabled-partial-overview/button-toggle-disabled-partial-overview-example.css
  packages/docs-examples/components/button-toggle/button-toggle-disabled-partial-overview/button-toggle-disabled-partial-overview-example.html
  packages/docs-examples/components/button-toggle/button-toggle-overview/button-toggle-overview-example.css
  packages/docs-examples/components/button-toggle/button-toggle-overview/button-toggle-overview-example.html
  packages/docs-examples/components/button-toggle/button-toggle-tooltip-overview/button-toggle-tooltip-overview-example.css
  packages/docs-examples/components/button-toggle/button-toggle-tooltip-overview/button-toggle-tooltip-overview-example.html
  packages/docs-examples/components/button-toggle/button-toggle-tooltip-overview/button-toggle-tooltip-overview-example.ts
  packages/docs-examples/components/button-toggle/index.ts
Labels: documentation

#47 docs(navbar): new article (#DS-1570)
  packages/components-dev/navbar/styles.scss
  packages/components/navbar/navbar.md
  packages/components/navbar/vertical-navbar.scss
  packages/docs-examples/components/navbar/navbar-overview/navbar-overview-example.css
  packages/docs-examples/components/navbar/navbar-overview/navbar-overview-example.html
  packages/docs-examples/components/navbar/navbar-vertical/navbar-vertical-example.css
  packages/docs-examples/components/navbar/navbar-vertical/navbar-vertical-example.html
  packages/docs-examples/example-module.ts
Labels: documentation

#77 fix(icon): warning style (DS-2485)
  apps/docs/src/styles/koobiq/default-theme/css-tokens.css
  packages/components/core/styles/theming/_components-theming.scss
Labels: bug

#78 fix(docs) incorrect indentation for dropdown buttons (#DS-2526)
  packages/docs-examples/components/popover/popover-scroll/popover-scroll-example.css
Labels: bug

#82 fix(docs,chore): marked update (#DS-2536)
  apps/docs/src/assets/stackblitz/package.json
  package.json
  packages/components/package.json
  tools/highlight-files/highlight-code-block.ts
  tools/markdown-to-html/marked/configuration.ts
  tools/markdown-to-html/marked/docs-marked-renderer.ts
  tools/markdown-to-html/utils.ts
  yarn.lock
Labels: dependencies

#83 fix(validation): alert styles (#DS-2540)
  packages/components/core/validation/validation.md
  packages/docs-examples/components/validation/index.ts
  packages/docs-examples/components/validation/validation-global-one-required/validation-global-one-required-example.css
  packages/docs-examples/components/validation/validation-global-one-required/validation-global-one-required-example.html
  packages/docs-examples/components/validation/validation-global/validation-global-example.css
  packages/docs-examples/components/validation/validation-global/validation-global-example.html
  packages/docs-examples/components/validation/validation-global/validation-global-example.ts
Labels: bug

#75 fix(dropdown,list): caption layout & heading, subheading fonts/colors (#DS-2461)
  apps/docs/src/assets/stackblitz/package.json
  apps/docs/src/styles/koobiq/default-theme/_variables.scss
  apps/docs/src/styles/koobiq/default-theme/index.d.ts
  apps/docs/src/styles/koobiq/default-theme/js/index.js
  package.json
  packages/components-dev/dropdown/template.html
  packages/components/dropdown/_dropdown-theme.scss
  packages/components/list/_list-theme.scss
  packages/components/package.json
  packages/docs-examples/components/dropdown/dropdown-navigation-wrap/dropdown-navigation-wrap-example.html
  packages/docs-examples/components/dropdown/dropdown-overview/dropdown-overview-example.html
  yarn.lock
Labels: bug

#92 fix(alert): colors in dark theme (#DS-2555)
  packages/components/alert/_alert-theme.scss
  packages/components/alert/alert.component.scss
Labels: bug

#85 fix(code-block): "show all" position when expanded (#DS-2518)
  packages/components/code-block/code-block.scss
Labels: bug

#104 fix(date-formatter):  "june", "july" in ru-RU Date short format (#DS-2596)
  apps/docs/src/assets/stackblitz/package.json
  package.json
  packages/angular-luxon-adapter/package.json
  packages/angular-moment-adapter/package.json
  packages/components/package.json
  yarn.lock
Labels: bug, dependencies
