Repository koobiq/angular-components, pull requests merged in 2024-09, with the labels that each got.

#244 feat(visual, navbar): applied new tokens for components, updated navbar styles (#DS-2786)
  apps/docs/src/app/containers/icons-viewer/icons-viewer-theme.scss
  apps/docs/src/assets/stackblitz/package.json
  apps/docs/src/styles/koobiq/default-theme/_md-typography.scss
  apps/docs/src/styles/koobiq/default-theme/_palette.scss
  apps/docs/src/styles/koobiq/default-theme/_typography.scss
  apps/docs/src/styles/koobiq/default-theme/_variables.scss
  apps/docs/src/styles/koobiq/default-theme/css-tokens-dark.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-font.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-light.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens.css
  apps/docs/src/styles/koobiq/default-theme/index.d.ts
  apps/docs/src/styles/koobiq/default-theme/js/index.js
  package.json
  packages/components/core/styles/theming/_theming.scss
  packages/components/navbar/_navbar-theme.scss
  packages/components/package.json
  packages/components/table/_table-theme.scss
  yarn.lock
Labels: bug

#243 fix(modal): return type (#DS-2702)
  .commitlintrc.js
  apps/docs/src/app/containers/icons-viewer/icons-viewer.component.ts
  packages/components/modal/modal-ref.class.ts
  packages/components/modal/modal.service.ts
  packages/components/modal/modal.type.ts
  tools/public_api_guard/components/modal.api.md
Labels: bug

#208 feat(visual): theming with CSS variables (#DS-2679)
  docs/guides/theming-2.0.md
  package.json
  packages/components-dev/index.html
  packages/components/alert/_alert-theme.scss
  packages/components/alert/alert-tokens.scss
  packages/components/alert/alert.component.scss
  packages/components/alert/alert.component.ts
  packages/components/core/common-behaviors/common-module.ts
  packages/components/core/styles/_koobiq-theme.scss
  tools/cspell-locales/ru.json
  tools/tokens/build-each-component.js
Labels: enhancement

#262 feat(checkbox,button-toggle,button,badge,autocomplete): components theming with CSS-vars (#DS-2805)
  docs/guides/theming-2.0.md
  packages/components/autocomplete/_autocomplete-theme.scss
  packages/components/autocomplete/autocomplete-tokens.scss
  packages/components/autocomplete/autocomplete.component.ts
  packages/components/autocomplete/autocomplete.scss
  packages/components/badge/_badge-theme.scss
  packages/components/badge/badge-tokens.scss
  packages/components/badge/badge.component.scss
  packages/components/badge/badge.component.ts
  packages/components/button-toggle/_button-toggle-theme.scss
  packages/components/button-toggle/button-toggle-tokens.scss
  packages/components/button-toggle/button-toggle.component.ts
  packages/components/button-toggle/button-toggle.scss
  packages/components/button/_button-theme.scss
  packages/components/button/button-tokens.scss
  packages/components/button/button.component.ts
  packages/components/button/button.scss
  packages/components/checkbox/_checkbox-theme.scss
  packages/components/checkbox/checkbox-tokens.scss
  packages/components/checkbox/checkbox.scss
  packages/components/checkbox/checkbox.ts
  packages/components/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
  packages/components/core/selection/pseudo-checkbox/pseudo-checkbox-tokens.scss
  packages/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
  packages/components/core/selection/pseudo-checkbox/pseudo-checkbox.ts
  packages/components/core/styles/_koobiq-theme.scss
  tools/tokens/build-each-component.js
  tools/tokens/utils.js
Labels: enhancement

#263 fix(button-toggle): focus styling (#DS-2776)
  packages/components/button-toggle/button-toggle.scss
Labels: bug

#267 feat(visual): components theming with CSS-vars (#DS-2817
  docs/guides/theming-2.0.md
  packages/components/badge/badge-tokens.scss
  packages/components/core/highlight/_highlight-theme.scss
  packages/components/core/styles/_koobiq-theme.scss
  packages/components/datepicker/_datepicker-theme.scss
  packages/components/datepicker/calendar.scss
  packages/components/datepicker/datepicker-content.scss
  packages/components/datepicker/datepicker-tokens.scss
  packages/components/datepicker/datepicker.component.ts
  packages/components/dropdown/_dropdown-theme.scss
  packages/components/dropdown/dropdown-tokens.scss
  packages/components/dropdown/dropdown.component.ts
  packages/components/dropdown/dropdown.scss
  packages/components/form-field/_form-field-theme.scss
  packages/components/form-field/_hint-theme.scss
  packages/components/form-field/form-field-tokens.scss
  packages/components/form-field/form-field.scss
  packages/components/form-field/form-field.ts
  packages/components/form-field/hint-tokens.scss
  packages/components/form-field/hint.scss
  packages/components/form-field/hint.ts
  packages/components/icon/_icon-button-theme.scss
  packages/components/icon/_icon-item-theme.scss
  packages/components/icon/_icon-theme.scss
  packages/components/icon/icon-button-tokens.scss
  packages/components/icon/icon-button.component.ts
  packages/components/icon/icon-button.scss
  packages/components/icon/icon-item-tokens.scss
  packages/components/icon/icon-item.component.ts
  packages/components/icon/icon-item.scss
  packages/components/icon/icon-tokens.scss
  packages/components/icon/icon.component.ts
  packages/components/icon/icon.scss
  packages/components/input/_input-theme.scss
  packages/components/input/input-tokens.scss
  packages/components/input/input.scss
  packages/components/link/_link-theme.scss
  packages/components/link/link-tokens.scss
  tools/tokens/build-each-component.js
  tools/tokens/utils.js
Labels: enhancement

#266 feat(docs): theme switch refactoring (#DS-2796)
  apps/docs/src/app/components/navbar/navbar.component.ts
  apps/docs/src/app/components/welcome/welcome.component.ts
  apps/docs/src/index.html
  apps/docs/src/main.scss
  apps/docs/src/styles/_docsearch.scss
  docs/guides/theming.md
  packages/components/core/services/theme.service.ts
  tools/public_api_guard/components/core.api.md
Labels: documentation

#285 feat(visual): components theming with CSS-vars (#DS-2823)
  docs/guides/theming-2.0.md
  packages/components/core/styles/_koobiq-theme.scss
  packages/components/list/_list-theme.scss
  packages/components/list/list-selection.component.ts
  packages/components/list/list-tokens.scss
  packages/components/list/list.component.ts
  packages/components/list/list.scss
  packages/components/loader-overlay/_loader-overlay-theme.scss
  packages/components/loader-overlay/loader-overlay-tokens.scss
  packages/components/loader-overlay/loader-overlay.component.ts
  packages/components/loader-overlay/loader-overlay.scss
  packages/components/markdown/_markdown-theme.scss
  packages/components/markdown/markdown-tokens.scss
  packages/components/markdown/markdown.component.ts
  packages/components/markdown/markdown.scss
  packages/components/modal/_modal-confirm.scss
  packages/components/modal/_modal-theme.scss
  packages/components/modal/modal-tokens.scss
  packages/components/modal/modal.component.ts
  packages/components/modal/modal.scss
  packages/components/navbar/_navbar-theme.scss
  packages/components/navbar/navbar-divider.scss
  packages/components/navbar/navbar-item.scss
  packages/components/navbar/navbar-tokens.scss
  packages/components/navbar/navbar.component.ts
  packages/components/navbar/navbar.scss
  packages/components/navbar/vertical-navbar.scss
  packages/components/popover/_popover-theme.scss
  packages/components/popover/popover-confirm.component.html
  packages/components/popover/popover-confirm.component.ts
  packages/components/popover/popover-tokens.scss
  packages/components/popover/popover.component.ts
  packages/components/popover/popover.scss
  tools/tokens/build-each-component.js
  tools/tokens/utils.js
Labels: enhancement

#291 fix(markdown): fixed markdown tokens initialization
  packages/components/core/styles/_koobiq-theme.scss
  packages/components/markdown/_markdown-theme.scss
  packages/components/markdown/markdown.scss
Labels: bug

#286 feat(visual): components theming with CSS-vars (#DS-2829)
  docs/guides/theming-2.0.md
  packages/components/core/styles/_koobiq-theme.scss
  packages/components/progress-bar/_progress-bar-theme.scss
  packages/components/progress-bar/progress-bar-tokens.scss
  packages/components/progress-bar/progress-bar.component.ts
  packages/components/progress-bar/progress-bar.scss
  packages/components/progress-spinner/_progress-spinner-theme.scss
  packages/components/progress-spinner/progress-spinner-tokens.scss
  packages/components/progress-spinner/progress-spinner.component.ts
  packages/components/progress-spinner/progress-spinner.scss
  packages/components/radio/_radio-theme.scss
  packages/components/radio/radio-tokens.scss
  packages/components/radio/radio.component.ts
  packages/components/radio/radio.scss
  packages/components/risk-level/_risk-level-theme.scss
  packages/components/risk-level/risk-level-tokens.scss
  packages/components/risk-level/risk-level.component.scss
  packages/components/risk-level/risk-level.component.ts
  packages/components/select/_select-theme.scss
  packages/components/select/select-tokens.scss
  packages/components/select/select.component.ts
  packages/components/select/select.scss
  packages/components/sidepanel/_sidepanel-theme.scss
  packages/components/sidepanel/sidepanel-container.component.ts
  packages/components/sidepanel/sidepanel-tokens.scss
  packages/components/sidepanel/sidepanel.scss
  tools/tokens/build-each-component.js
  tools/tokens/utils.js
Labels: enhancement

#287 feat(visual): components theming with CSS-vars (#DS-2845)
  docs/guides/theming-2.0.md
  packages/components-dev/forms/template.html
  packages/components/core/forms/_forms-theme.scss
  packages/components/core/forms/_forms.scss
  packages/components/core/forms/forms-tokens.scss
  packages/components/core/option/_optgroup-theme.scss
  packages/components/core/option/_option-action-theme.scss
  packages/components/core/option/_option-theme.scss
  packages/components/core/option/action.scss
  packages/components/core/option/action.ts
  packages/components/core/option/optgroup-tokens.scss
  packages/components/core/option/optgroup.scss
  packages/components/core/option/optgroup.ts
  packages/components/core/option/option-action-tokens.scss
  packages/components/core/option/option-tokens.scss
  packages/components/core/option/option.scss
  packages/components/core/option/option.ts
  packages/components/core/styles/_koobiq-theme.scss
  packages/components/core/styles/theming/_scrollbar-theme.scss
  packages/components/core/styles/theming/scrollbar-tokens.scss
  packages/components/form-field/form-field-tokens.scss
  packages/components/scrollbar/_scrollbar-component-theme.scss
  packages/components/scrollbar/scrollbar-tokens.scss
  packages/components/scrollbar/scrollbar.component.scss
  packages/components/scrollbar/scrollbar.component.ts
  tools/tokens/build-each-component.js
  tools/tokens/utils.js
Labels: enhancement

#295 feat(visual): components theming with CSS-vars (#DS-2833)
  docs/guides/theming-2.0.md
  packages/components-dev/tabs/template.html
  packages/components-dev/tag/template.html
  packages/components/core/styles/_koobiq-theme.scss
  packages/components/form-field/form-field.ts
  packages/components/splitter/_splitter-theme.scss
  packages/components/splitter/splitter-tokens.scss
  packages/components/splitter/splitter.component.ts
  packages/components/splitter/splitter.scss
  packages/components/tabs/_tabs-common.scss
  packages/components/tabs/_tabs-theme.scss
  packages/components/tabs/tab-group.component.ts
  packages/components/tabs/tab-group.scss
  packages/components/tabs/tab-header.scss
  packages/components/tabs/tab-nav-bar/tab-nav-bar.scss
  packages/components/tabs/tab-nav-bar/tab-nav-bar.ts
  packages/components/tabs/tabs-tokens.scss
  packages/components/tags/_tag-theme.scss
  packages/components/tags/tag-input-tokens.scss
  packages/components/tags/tag-list.component.ts
  packages/components/tags/tag-list.scss
  packages/components/tags/tag-tokens.scss
  packages/components/tags/tag.scss
  tools/tokens/build-each-component.js
  tools/tokens/utils.js
Labels: enhancement

#304 fix(navbar): added tokens to vertical navbar
  packages/components/navbar/vertical-navbar.component.ts
Labels: bug

#302 fix(docs,cli,scrolling): stick to specific scrollbar lib version (#DS-2899)
  apps/docs/src/assets/stackblitz/src/koobiq.module.ts
  package.json
  packages/components-dev/scrollbar/module.ts
  packages/components-dev/scrollbar/template.html
  packages/components/package.json
  packages/components/scrollbar/scrollbar.component.ts
  packages/components/scrollbar/scrollbar.directive.ts
  packages/components/scrollbar/scrollbar.md
  packages/components/scrollbar/scrollbar.types.ts
  packages/docs-examples/components/scrollbar/index.ts
  packages/docs-examples/components/scrollbar/scrollbar-input-customization/scrollbar-input-customization-example.ts
  packages/docs-examples/components/scrollbar/scrollbar-module-customization/scrollbar-module-customization-example.ts
  packages/docs-examples/components/scrollbar/scrollbar-overview/scrollbar-overview-example.css
  packages/docs-examples/components/scrollbar/scrollbar-overview/scrollbar-overview-example.html
  packages/docs-examples/components/scrollbar/scrollbar-overview/scrollbar-overview-example.ts
  packages/docs-examples/components/scrollbar/scrollbar-scroll-to-top/scrollbar-scroll-to-top-example.css
  packages/docs-examples/components/scrollbar/scrollbar-scroll-to-top/scrollbar-scroll-to-top-example.html
  packages/docs-examples/components/scrollbar/scrollbar-scroll-to-top/scrollbar-scroll-to-top-example.ts
  packages/docs-examples/example-module.ts
  packages/schematics/rollup.config.js
  tools/cspell-locales/en.json
  tools/public_api_guard/components/scrollbar.api.md
  yarn.lock
Labels: documentation, dependencies

#298 feat: angular 18 (#DS-2894)
  .eslintignore
  .nvmrc
  angular.json
  apps/docs/src/app/components/docs-live-example-viewer/docs-live-example-viewer.ts
  apps/docs/src/assets/stackblitz/angular.json
  apps/docs/src/index.html
  package.json
  packages/cli/package.json
  packages/components-dev/index.html
  packages/components/autocomplete/autocomplete.karma-spec.ts
  packages/components/core/common-behaviors/index.ts
  packages/components/dropdown/dropdown.karma-spec.ts
  packages/components/select/select.component.karma-spec.ts
  tools/api-gen/extraction/index.ts
  tools/api-gen/rendering/transforms/code-transforms.ts
  tools/api-gen/rendering/transforms/member-transforms.ts
  tools/api-gen/rendering/transforms/params-transforms.ts
  tools/public_api_guard/components/scrollbar.api.md
  yarn.lock
Labels: breaking changes

#309 fix(list): multiple selection by keyboard on macos (#DS-2908)
  packages/components-dev/list/template.html
  packages/components/list/list-selection.component.ts
  tools/public_api_guard/components/list.api.md
Labels: 17.x, 18.x

#307 feat(scrollbar): updated docs and migrated to standalone (#DS-2899)
  .commitlintrc.js
  apps/docs/src/app/components/documentation-items.ts
  apps/docs/src/assets/stackblitz/src/koobiq.module.ts
  package.json
  packages/components-dev/scrollbar/main.ts
  packages/components-dev/scrollbar/module.ts
  packages/components-dev/scrollbar/styles.scss
  packages/components-dev/scrollbar/template.html
  packages/components/package.json
  packages/components/scrollbar/examples.scrollbar.md
  packages/components/scrollbar/scrollbar.component.spec.ts
  packages/components/scrollbar/scrollbar.component.ts
  packages/components/scrollbar/scrollbar.directive.ts
  packages/components/scrollbar/scrollbar.md
  packages/components/scrollbar/scrollbar.module.ts
  packages/docs-examples/components/scrollbar/index.ts
  packages/docs-examples/components/scrollbar/scrollbar-overview/scrollbar-overview-example.css
  packages/docs-examples/components/scrollbar/scrollbar-overview/scrollbar-overview-example.html
  packages/docs-examples/components/scrollbar/scrollbar-overview/scrollbar-overview-example.ts
  packages/docs-examples/components/scrollbar/scrollbar-scroll-to-top/scrollbar-scroll-to-top-example.css
  packages/docs-examples/components/scrollbar/scrollbar-scroll-to-top/scrollbar-scroll-to-top-example.html
  packages/docs-examples/components/scrollbar/scrollbar-scroll-to-top/scrollbar-scroll-to-top-example.ts
  packages/docs-examples/components/scrollbar/scrollbar-with-custom-config/scrollbar-with-custom-config-example.ts
  packages/docs-examples/components/scrollbar/scrollbar-with-options/scrollbar-with-options-example.ts
  packages/docs-examples/example-module.ts
  tools/cspell-locales/en.json
  tools/public_api_guard/components/scrollbar.api.md
  yarn.lock
Labels: 17.x, 18.x
