Repository koobiq/angular-components, pull requests merged in 2024-07, with the labels that each got.

#99 feat(visual): update sizes for components (#DS-2168)
  apps/docs/src/assets/stackblitz/package.json
  package.json
  packages/components/alert/alert.component.scss
  packages/components/badge/badge.component.scss
  packages/components/button-toggle/button-toggle.scss
  packages/components/checkbox/checkbox.scss
  packages/components/dropdown/dropdown-item.scss
  packages/components/file-upload/multiple-file-upload.component.scss
  packages/components/form-field/hint.scss
  packages/components/list/list.scss
  packages/components/navbar/_navbar-item_horizontal.scss
  packages/components/navbar/_navbar-item_vertical.scss
  packages/components/navbar/navbar-brand.scss
  packages/components/package.json
  packages/components/radio/radio.scss
  packages/components/select/select.component.spec.ts
  yarn.lock
Labels: enhancement

#109 feat(tabs): use tabId as selection key (#DS-1036)
  apps/docs/src/app/components/documentation-items.ts
  packages/components/tabs/examples.tabs.md
  packages/components/tabs/tab-group.component.ts
  packages/components/tabs/tab-group.html
  packages/components/tabs/tab-group.spec.ts
  packages/docs-examples/components/tabs/index.ts
  packages/docs-examples/components/tabs/tab-active-tab-index/tab-active-tab-index-example.css
  packages/docs-examples/components/tabs/tab-active-tab-index/tab-active-tab-index-example.html
  packages/docs-examples/components/tabs/tab-active-tab-index/tab-active-tab-index-example.ts
  packages/docs-examples/components/tabs/tab-active-tab/tab-active-tab-example.css
  packages/docs-examples/components/tabs/tab-active-tab/tab-active-tab-example.html
  packages/docs-examples/components/tabs/tab-active-tab/tab-active-tab-example.ts
  packages/docs-examples/example-module.ts
  tools/public_api_guard/components/tabs.api.md
Labels: enhancement

#115 fix: box-shadow gpu lines
  apps/docs/src/assets/stackblitz/package.json
  package.json
  packages/components/card/_card-theme.scss
  packages/components/code-block/_code-block-theme.scss
  packages/components/form-field/_form-field-theme.scss
  packages/components/icon/_icon-button-theme.scss
  packages/components/package.json
  packages/components/tags/_tag-theme.scss
  packages/components/toggle/_toggle-theme.scss
  yarn.lock
Labels: bug

#91 feat(docs): New Sections for Radio Component (#DS-1483)
  packages/components/radio/radio.md
  packages/docs-examples/components/radio/index.ts
  packages/docs-examples/components/radio/radio-content/radio-content-example.css
  packages/docs-examples/components/radio/radio-content/radio-content-example.html
  packages/docs-examples/components/radio/radio-content/radio-content-example.ts
  packages/docs-examples/components/radio/radio-group/radio-group-example.css
  packages/docs-examples/components/radio/radio-group/radio-group-example.html
  packages/docs-examples/components/radio/radio-group/radio-group-example.ts
  packages/docs-examples/components/radio/radio-invalid/radio-invalid-example.css
  packages/docs-examples/components/radio/radio-invalid/radio-invalid-example.html
  packages/docs-examples/components/radio/radio-invalid/radio-invalid-example.ts
  packages/docs-examples/components/radio/radio-required/radio-required-example.css
  packages/docs-examples/components/radio/radio-required/radio-required-example.html
  packages/docs-examples/components/radio/radio-required/radio-required-example.ts
  packages/docs-examples/components/radio/radio-size/radio-size-example.css
  packages/docs-examples/components/radio/radio-size/radio-size-example.html
  packages/docs-examples/components/radio/radio-size/radio-size-example.ts
  packages/docs-examples/components/radio/radio-style/radio-style-example.css
  packages/docs-examples/components/radio/radio-style/radio-style-example.html
  packages/docs-examples/components/radio/radio-style/radio-style-example.ts
  packages/docs-examples/example-module.ts
Labels: documentation

#96 fix(toast): improved toastService timer performance (#DS-2521)
  packages/components/toast/toast.service.ts
  packages/components/toast/toast.spec.ts
  tools/public_api_guard/components/toast.api.md
Labels: bug

#107 feat(docs): added algolia docsearch support (#DS-2503)
  apps/docs/src/app/components/component-viewer/component-viewer.component.ts
  apps/docs/src/app/components/component-viewer/component-viewer.template.html
  apps/docs/src/app/components/docsearch/docsearch.component.scss
  apps/docs/src/app/components/docsearch/docsearch.component.ts
  apps/docs/src/app/components/navbar/navbar.module.ts
  apps/docs/src/app/components/navbar/navbar.scss
  apps/docs/src/app/components/navbar/navbar.template.html
  apps/docs/src/app/components/sidenav/sidenav.component.html
  apps/docs/src/index.html
  apps/docs/src/main.scss
  apps/docs/src/robots.txt
  apps/docs/src/styles/_docsearch.scss
  apps/docs/tsconfig.json
  docs/guides/versioning.en.md
  docs/guides/versioning.md
  firebase.json
  package.json
  packages/components/core/locales/locale-service.spec.ts
  packages/components/core/locales/locale-service.ts
  packages/components/core/validation/validation.md
  packages/components/datepicker/datepicker.md
  packages/components/file-upload/file-upload.md
  packages/components/modal/modal.md
  packages/components/popover/popover.md
  packages/components/timepicker/timepicker.md
  packages/components/tooltip/tooltip.md
  tools/cspell-locales/en.json
  yarn.lock
Labels: documentation

#118 feat(docs): auto hiding scrollbar in docs sidenav menu (#DS-2589)
  apps/docs/src/app/components/sidenav/sidenav.component.html
  apps/docs/src/app/components/sidenav/sidenav.component.ts
  apps/docs/src/app/components/sidenav/sidenav.module.ts
  packages/components/scrollbar/scrollbar.component.scss
Labels: documentation, enhancement

#125 feat(tag-input,autocomplete): disable tag creation by the paste event (#DS-2455)
  apps/docs/src/app/components/documentation-items.ts
  packages/components-dev/tag/module.ts
  packages/components-dev/tag/styles.scss
  packages/components-dev/tag/tag-input-default-options-override.template.html
  packages/components-dev/tag/template.html
  packages/components/tags/examples.tag-autocomplete.md
  packages/components/tags/examples.tag-input.md
  packages/components/tags/tag-default-options.ts
  packages/components/tags/tag-input.spec.ts
  packages/components/tags/tag-input.ts
  packages/docs-examples/components/tag/index.ts
  packages/docs-examples/components/tag/tags-autocomplete-onpaste-off/tags-autocomplete-onpaste-off-example.css
  packages/docs-examples/components/tag/tags-autocomplete-onpaste-off/tags-autocomplete-onpaste-off-example.html
  packages/docs-examples/components/tag/tags-autocomplete-onpaste-off/tags-autocomplete-onpaste-off-example.ts
  packages/docs-examples/components/tag/tags-input-onpaste-off/tags-input-onpaste-off-example.css
  packages/docs-examples/components/tag/tags-input-onpaste-off/tags-input-onpaste-off-example.html
  packages/docs-examples/components/tag/tags-input-onpaste-off/tags-input-onpaste-off-example.ts
  packages/docs-examples/example-module.ts
  tools/public_api_guard/components/tags.api.md
Labels: enhancement

#126 fix(checkbox): added background to pseudo (#DS-2643)
  packages/components/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
Labels: bug

#114 feat(docs): theming article rewrite (#DS-2544)
  apps/docs/src/app/components/documentation-items.ts
  docs/guides/customization.md
  docs/guides/theming.md
  packages/components/core/services/theme.service.ts
  tools/cspell-locales/ru.json
  tools/public_api_guard/components/core.api.md
Labels: documentation

#135 fix(select): "show more" text calculations (#DS-2649)
  packages/components/select/select.component.ts
  packages/components/tree-select/tree-select.component.ts
  tools/public_api_guard/components/select.api.md
  tools/public_api_guard/components/tree-select.api.md
Labels: bug

#140 fix(docs,toast): single stack of toasts (#DS-2541)
  apps/docs/src/app/docs.module.ts
  packages/docs-examples/components/toast/index.ts
Labels: bug, documentation

#142 fix(docs): example start command change (#DS-2529)
  apps/docs/src/app/components/stackblitz/stackblitz-writer.ts
  firebase.json
Labels: documentation

#144 feat(timepicker): placeholder and view value localization (#DS-2059)
  packages/components/core/locales/ru-RU.ts
  packages/components/timepicker/timepicker.constants.ts
  packages/components/timepicker/timepicker.directive.ts
  packages/components/timepicker/timepicker.spec.ts
  tools/public_api_guard/components/timepicker.api.md
Labels: enhancement

#150 feat(docs): updated example code block show (#DS-2602)
  apps/docs/src/app/components/docs-live-example-viewer/docs-live-example-viewer.html
  apps/docs/src/app/components/docs-live-example-viewer/docs-live-example-viewer.ts
  packages/docs-examples/components/card/card-overview/card-overview-example.css
  packages/docs-examples/components/table/table-full-width/table-full-width-example.css
  packages/docs-examples/components/table/table-with-borders/table-with-borders-example.css
Labels: documentation

#148 fix(docs): examples, api sections selection and scroll after link opened (#DS-2478)
  apps/docs/src/app/components/anchors/anchors.component.ts
  apps/docs/src/app/components/documentation-items.ts
  apps/docs/src/app/components/sidenav/sidenav.component.ts
Labels: bug, documentation

#146 fix(docs): update tokens for disabled radio (#DS-2635)
  apps/docs/src/styles/koobiq/default-theme/_md-typography.scss
  apps/docs/src/styles/koobiq/default-theme/_typography.scss
  apps/docs/src/styles/koobiq/default-theme/_variables.scss
  apps/docs/src/styles/koobiq/default-theme/css-tokens-dark.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-font.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-light.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens.css
  apps/docs/src/styles/koobiq/default-theme/index.d.ts
  apps/docs/src/styles/koobiq/default-theme/js/index.js
Labels: documentation

#157 fix(tree-select): localization for hiddenItemsText (#DS-2680)
  packages/components-dev/tree-select/template.html
  packages/components/tree-select/tree-select.component.spec.ts
  packages/components/tree-select/tree-select.component.ts
  tools/public_api_guard/components/tree-select.api.md
Labels: bug

#103 fix(docs): alert - article and examples (#DS-2584)
  packages/components-dev/link/template.html
  packages/components/alert/alert.component.html
  packages/components/alert/alert.component.scss
  packages/components/alert/alert.component.ts
  packages/components/alert/alert.md
  packages/components/link/_link-theme.scss
  packages/docs-examples/components/alert/alert-close/alert-close-example.html
  packages/docs-examples/components/alert/alert-content/alert-content-example.css
  packages/docs-examples/components/alert/alert-content/alert-content-example.html
  packages/docs-examples/components/alert/alert-size/alert-size-example.css
  packages/docs-examples/components/alert/alert-size/alert-size-example.html
  packages/docs-examples/components/alert/alert-status/alert-status-example.css
  packages/docs-examples/components/alert/alert-status/alert-status-example.ts
  packages/docs-examples/components/alert/alert-variants/alert-variants-example.css
  packages/docs-examples/components/alert/alert-variants/alert-variants-example.html
  packages/docs-examples/components/alert/alert-variants/alert-variants-example.ts
  tools/cspell-locales/ru.json
Labels: documentation
