Repository koobiq/angular-components, pull requests merged in 2024-11, with the labels that each got.

#405 fix(loader-overlay): align border-radius with parentElement (#DS-2734)
  packages/components/loader-overlay/loader-overlay.scss
Labels: 18.x

#411 fix(tree,icon): aligned icons color with design (#DS-2875)
  packages/components/tree/_tree-theme.scss
  packages/components/tree/tree-option.scss
Labels: bug, 18.x

#415 feat(docs): bootstrap standalone examples
  angular.json
  apps/docs/src/app/components/doc-example-viewer/doc-example-viewer.ts
  apps/docs/src/app/components/docs-live-example-viewer/docs-live-example-viewer.html
  apps/docs/src/app/components/docs-live-example-viewer/docs-live-example-viewer.ts
  apps/docs/src/app/components/stackblitz/normalize-path.ts
  apps/docs/src/app/components/stackblitz/stackblitz-button.ts
  apps/docs/src/app/components/stackblitz/stackblitz-writer.ts
  apps/docs/src/assets/stackblitz/angular.json
  apps/docs/src/assets/stackblitz/src/app/app.module.ts
  apps/docs/src/assets/stackblitz/src/assets/.gitkeep
  apps/docs/src/assets/stackblitz/src/environments/environment.prod.ts
  apps/docs/src/assets/stackblitz/src/environments/environment.ts
  apps/docs/src/assets/stackblitz/src/index.html
  apps/docs/src/assets/stackblitz/src/koobiq.module.ts
  apps/docs/src/assets/stackblitz/src/main.ts
  apps/docs/src/assets/stackblitz/src/styles.scss
  package.json
  packages/docs-examples/components/badge/badge-content/badge-content-example.ts
  packages/docs-examples/components/badge/badge-fill-and-style/badge-fill-and-style-example.ts
  packages/docs-examples/components/badge/badge-size/badge-size-example.ts
  packages/docs-examples/components/badge/badge-table/badge-table-example.ts
  packages/docs-examples/components/badge/badge-tooltip/badge-tooltip-example.ts
  packages/docs-examples/example-module.ts
  tools/example-module/example-module.template
  tools/example-module/generate-example-module.ts
  tools/example-module/parse-example-module-file.ts
  yarn.lock
Labels: 18.x

#387 fix(visual): removed component tokens usage from code (#DS-2996)
  apps/docs/scripts/build-tokens.js
  apps/docs/src/app/containers/icons-viewer/icons-viewer-theme.scss
  apps/docs/src/app/containers/icons-viewer/icons-viewer.scss
  apps/docs/src/styles/_hot-keys.scss
  apps/docs/src/styles/koobiq/default-theme/_variables.scss
  apps/docs/src/styles/koobiq/default-theme/css-tokens-dark.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-font.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-light.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens.css
  apps/docs/src/styles/koobiq/default-theme/js/index.js
  docs/guides/theming.md
  packages/components-experimental/form-field/form-field-tokens.scss
  packages/components/button-toggle/button-toggle-tokens.scss
  packages/components/button/button-tokens.scss
  packages/components/code-block/code-block-tokens.scss
  packages/components/code-block/code-block.scss
  packages/components/core/forms/_forms.scss
  packages/components/core/forms/forms-tokens.scss
  packages/components/core/option/action.scss
  packages/components/core/option/action.ts
  packages/components/core/option/optgroup-tokens.scss
  packages/components/core/option/optgroup.ts
  packages/components/core/option/option-action-tokens.scss
  packages/components/core/option/option-tokens.scss
  packages/components/core/option/option.ts
  packages/components/core/styles/common/_groups.scss
  packages/components/core/styles/common/_popup.scss
  packages/components/core/styles/common/_select.scss
  packages/components/dropdown/dropdown-tokens.scss
  packages/components/dropdown/dropdown.component.ts
  packages/components/file-upload/multiple-file-upload.component.scss
  packages/components/form-field/form-field-tokens.scss
  packages/components/input/input.scss
  packages/components/markdown/_markdown-theme.scss
  packages/components/markdown/markdown-tokens.scss
  packages/components/navbar/navbar-tokens.scss
  packages/components/popover/popover-tokens.scss
  packages/components/popover/popover.scss
  packages/components/radio/radio-tokens.scss
  packages/components/radio/radio.scss
  packages/components/select/_select-theme.scss
  packages/components/select/select-tokens.scss
  packages/components/select/select.component.ts
  packages/components/select/select.scss
  packages/components/timezone/timezone-option-tokens.scss
  packages/components/toast/toast.component.scss
  packages/components/toggle/toggle.scss
  packages/components/tree-select/tree-select-tokens.scss
  packages/components/tree-select/tree-select.component.ts
  packages/components/tree/padding.directive.ts
  packages/components/tree/tree-option.scss
Labels: enhancement, 18.x

#424 fix: normal radio vertical gap
  packages/components/radio/radio-tokens.scss
Labels: bug

#438 fix(visual): md-typography styles prefix
  packages/components/core/styles/typography/_typography.scss
Labels: bug

#434 feat(schematics): added migration script for product-icons (#DS-3124)
  packages/schematics/rollup.config.js
  packages/schematics/scripts/copy-meta-to-dist.js
  packages/schematics/src/collection.json
  packages/schematics/src/migrations/css-selectors/index.ts
  packages/schematics/src/migrations/deprecated-icons/README.md
  packages/schematics/src/migrations/deprecated-icons/__snapshots__/index.spec.ts.snap
  packages/schematics/src/migrations/deprecated-icons/data.ts
  packages/schematics/src/migrations/deprecated-icons/index.spec.ts
  packages/schematics/src/migrations/deprecated-icons/index.ts
  packages/schematics/src/migrations/deprecated-icons/schema.json
  packages/schematics/src/migrations/deprecated-icons/schema.ts
  packages/schematics/src/migrations/new-icons-pack/README.md
  packages/schematics/src/migrations/new-icons-pack/data.ts
  packages/schematics/src/migrations/new-icons-pack/index.spec.ts
  packages/schematics/src/migrations/new-icons-pack/index.ts
  packages/schematics/src/migrations/new-icons-pack/schema.json
  packages/schematics/src/migrations/new-icons-pack/schema.ts
  packages/schematics/src/utils/messages.ts
  packages/schematics/src/utils/migrations.js
Labels: enhancement, 18.x

#453 fix(perf): components tokens usage optimization (#DS-3117)
  angular.json
  apps/docs/src/assets/stackblitz/angular.json
  apps/docs/src/assets/stackblitz/src/styles.scss
  apps/docs/src/main.scss
  apps/docs/src/styles/_docsearch.scss
  packages/components-experimental/form-field/form-field-tokens.scss
  packages/components-experimental/form-field/hint-tokens.scss
  packages/components/accordion/accordion-tokens.scss
  packages/components/alert/alert-tokens.scss
  packages/components/autocomplete/autocomplete-tokens.scss
  packages/components/badge/badge-tokens.scss
  packages/components/button-toggle/button-toggle-tokens.scss
  packages/components/button/button-tokens.scss
  packages/components/checkbox/checkbox-tokens.scss
  packages/components/code-block/code-block-tokens.scss
  packages/components/core/forms/forms-tokens.scss
  packages/components/core/option/option-tokens.scss
  packages/components/core/option/option.ts
  packages/components/core/selection/pseudo-checkbox/pseudo-checkbox-tokens.scss
  packages/components/core/styles/theming/scrollbar-tokens.scss
  packages/components/datepicker/datepicker-tokens.scss
  packages/components/divider/divider-tokens.scss
  packages/components/dl/dl-tokens.scss
  packages/components/dropdown/dropdown-tokens.scss
  packages/components/dropdown/dropdown.component.ts
  packages/components/empty-state/empty-state-tokens.scss
  packages/components/file-upload/file-upload-tokens.scss
  packages/components/form-field/form-field-tokens.scss
  packages/components/form-field/hint-tokens.scss
  packages/components/icon/icon-button-tokens.scss
  packages/components/icon/icon-item-tokens.scss
  packages/components/icon/icon-tokens.scss
  packages/components/link/link-tokens.scss
  packages/components/list/list-tokens.scss
  packages/components/loader-overlay/loader-overlay-tokens.scss
  packages/components/markdown/markdown-tokens.scss
  packages/components/modal/modal-tokens.scss
  packages/components/navbar/navbar-tokens.scss
  packages/components/popover/popover-tokens.scss
  packages/components/progress-bar/progress-bar-tokens.scss
  packages/components/progress-spinner/progress-spinner-tokens.scss
  packages/components/radio/radio-tokens.scss
  packages/components/risk-level/risk-level-tokens.scss
  packages/components/scrollbar/scrollbar-tokens.scss
  packages/components/select/select-tokens.scss
  packages/components/sidepanel/sidepanel-tokens.scss
  packages/components/tabs/tabs-tokens.scss
  packages/components/tags/tag-tokens.scss
  packages/components/timezone/timezone-option-tokens.scss
  packages/components/toast/toast-tokens.scss
  packages/components/toggle/toggle-tokens.scss
  packages/components/tooltip/tooltip-tokens.scss
  packages/components/tree-select/_tree-select-theme.scss
  packages/components/tree-select/tree-select-tokens.scss
  packages/components/tree/tree-tokens.scss
Labels: bug, 18.x

#451 feat(link): new icon for external link (#DS-3020)
  apps/docs/src/app/components/stackblitz/stackblitz-button.html
  apps/docs/src/app/components/stackblitz/stackblitz-button.ts
  apps/docs/src/assets/stackblitz/package.json
  package.json
  packages/components-dev/link/template.html
  packages/components/core/styles/_koobiq-theme.scss
  packages/components/link/_link-theme.scss
  packages/components/link/link.md
  packages/components/package.json
  packages/docs-examples/components/link/link-application/link-application-example.ts
  packages/docs-examples/components/link/link-caption/link-caption-example.ts
  packages/docs-examples/components/link/link-color/link-color-example.ts
  packages/docs-examples/components/link/link-external/link-external-example.ts
  packages/docs-examples/components/link/link-general/link-general-example.ts
  packages/docs-examples/components/link/link-icons/link-icons-example.ts
  packages/docs-examples/components/link/link-overview/link-overview-example.ts
  packages/docs-examples/components/link/link-target-blank/link-target-blank-example.ts
  packages/docs-examples/components/link/link-visited/link-visited-example.ts
  packages/docs-examples/components/select/select-footer/select-footer-example.html
  packages/docs-examples/components/tree-select/tree-select-footer-overview/tree-select-footer-overview-example.ts
  yarn.lock
Labels: enhancement, 18.x

#457 fix(select): customMatcher error (#DS-3179)
  packages/components/select/select.component.ts
  packages/components/tree-select/tree-select.component.ts
Labels: bug, 17.x, 18.x
