Repository koobiq/angular-components, pull requests merged in 2024-10, with the labels that each got.

#332 fix(tree): mouse click selection generates extra event (#DS-2900)
  packages/components/tree-select/tree-select.component.spec.ts
  packages/components/tree-select/tree-select.component.ts
  packages/components/tree/tree-option.component.ts
  tools/public_api_guard/components/tree-select.api.md
  tools/public_api_guard/components/tree.api.md
Labels: 17.x

#346 feat(visual): added css-vars for font-family tokens and added default value for global tokens in
  packages/components/alert/alert-tokens.scss
  packages/components/badge/badge-tokens.scss
  packages/components/button-toggle/button-toggle-tokens.scss
  packages/components/button/button-tokens.scss
  packages/components/checkbox/checkbox-tokens.scss
  packages/components/code-block/code-block-tokens.scss
  packages/components/core/forms/forms-tokens.scss
  packages/components/core/option/optgroup-tokens.scss
  packages/components/core/option/option-tokens.scss
  packages/components/core/selection/pseudo-checkbox/pseudo-checkbox-tokens.scss
  packages/components/datepicker/datepicker-tokens.scss
  packages/components/dl/dl-tokens.scss
  packages/components/dropdown/dropdown-tokens.scss
  packages/components/empty-state/empty-state-tokens.scss
  packages/components/file-upload/file-upload-tokens.scss
  packages/components/form-field/form-field-tokens.scss
  packages/components/form-field/hint-tokens.scss
  packages/components/input/input-tokens.scss
  packages/components/link/link-tokens.scss
  packages/components/list/list-tokens.scss
  packages/components/loader-overlay/loader-overlay-tokens.scss
  packages/components/markdown/markdown-tokens.scss
  packages/components/modal/modal-tokens.scss
  packages/components/navbar/navbar-tokens.scss
  packages/components/popover/popover-tokens.scss
  packages/components/progress-bar/progress-bar-tokens.scss
  packages/components/progress-spinner/progress-spinner-tokens.scss
  packages/components/radio/radio-tokens.scss
  packages/components/risk-level/risk-level-tokens.scss
  packages/components/select/select-tokens.scss
  packages/components/sidepanel/sidepanel-tokens.scss
  packages/components/table/table-tokens.scss
  packages/components/tabs/tabs-tokens.scss
  packages/components/tags/tag-input-tokens.scss
  packages/components/tags/tag-tokens.scss
  packages/components/textarea/textarea-tokens.scss
  packages/components/timezone/timezone-option-tokens.scss
  packages/components/toast/toast-tokens.scss
  packages/components/toggle/toggle-tokens.scss
  packages/components/tooltip/tooltip-tokens.scss
  packages/components/tree-select/tree-select-tokens.scss
  packages/components/tree/tree-tokens.scss
  tools/tokens/build-each-component.js
  tools/tokens/utils.js
Labels: bug, 17.x

#349 fix(docs): corrected system-dependent theme selection on startup (#DS-2952)
  apps/docs/src/index.html
Labels: bug, documentation, 18.x

#353 fix(timezone): added missing tokens
  apps/docs/scripts/build-tokens.js
  apps/docs/src/styles/koobiq/default-theme/_variables.scss
  apps/docs/src/styles/koobiq/default-theme/css-tokens-dark.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-font.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-light.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens.css
  apps/docs/src/styles/koobiq/default-theme/index.d.ts
  apps/docs/src/styles/koobiq/default-theme/js/index.js
  packages/components-dev/index.html
  packages/components-dev/main.scss
  packages/components/timezone/timezone-option-tokens.scss
  tools/tokens/utils.js
Labels: bug, 18.x

#354 fix(timezone): added missing tokens
  packages/components/timezone/timezone-option-tokens.scss
  tools/tokens/utils.js
Labels: bug, 17.x

#356 fix(alert): aligned close button according to design (#DS-2886)
  apps/docs/src/styles/koobiq/default-theme/css-tokens.css
  packages/components/alert/alert-tokens.scss
  packages/components/alert/alert.component.scss
Labels: bug, 18.x

#357 fix(alert): aligned close button according to design (#DS-2886)
  packages/components/alert/alert-tokens.scss
  packages/components/alert/alert.component.scss
Labels: bug, 17.x

#361 feat(modal): added shadows on scroll/overflow (#DS-2892)
  apps/docs/src/assets/stackblitz/package.json
  apps/docs/src/styles/koobiq/default-theme/_variables.scss
  apps/docs/src/styles/koobiq/default-theme/css-tokens-dark.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-font.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-light.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens.css
  apps/docs/src/styles/koobiq/default-theme/index.d.ts
  apps/docs/src/styles/koobiq/default-theme/js/index.js
  package.json
  packages/components/modal/_modal-theme.scss
  packages/components/modal/modal.component.ts
  packages/components/package.json
  yarn.lock
Labels: enhancement, 18.x

#358 feat(docs,dropdown): set button to active on dropdown opened (#DS-2709)
  packages/components-dev/dropdown/module.ts
  packages/components-dev/dropdown/template.html
  packages/components-dev/toast/template.html
  packages/components/button/button.component.spec.ts
  packages/components/button/button.dropdown-trigger.directive.ts
  packages/components/button/button.module.ts
  packages/components/button/public-api.ts
  packages/components/dropdown/dropdown.md
  packages/docs-examples/components/dropdown/dropdown-overview/dropdown-overview-example.html
  packages/docs-examples/components/dropdown/dropdown-overview/dropdown-overview-example.ts
  tools/public_api_guard/components/button.api.md
Labels: documentation, enhancement, 18.x

#372 fix(file-upload): mark single upload with kbq-error on hasError = tru…
  packages/components/file-upload/single-file-upload.component.html
Labels: bug, 18.x

#375 feat(input): added property [integer] (#DS-1915)
  packages/components-dev/input/template.html
  packages/components/input/input-number.spec.ts
  packages/components/input/input-number.ts
  packages/docs-examples/components/input/input-number-overview/input-number-overview-example.html
  packages/docs-examples/components/input/input-number-overview/input-number-overview-example.ts
  tools/public_api_guard/components/input.api.md
Labels: 17.x, 18.x

#378 fix(number-input): errors in "number-input" without localeService (#DS-3016)
  .commitlintrc.js
  packages/components/core/locales/locale-service.ts
  packages/components/input/input-number.ts
  tools/public_api_guard/components/core.api.md
  tools/public_api_guard/components/input.api.md
Labels: 17.x, 18.x

#381 feat(docs): updated docs for theming (#DS-2622)
  docs/guides/theming-deprecated.md
  docs/guides/theming.md
Labels: documentation, 18.x

#382 feat(docs,core): sync theme selectors in themeService with design-tokens package (#DS-3004)
  apps/docs/scripts/build-tokens.js
  apps/docs/src/app/components/welcome/welcome.component.ts
  apps/docs/src/main.scss
  apps/docs/src/styles/_docsearch.scss
  apps/docs/src/styles/koobiq/default-theme/css-tokens-dark.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-light.css
  docs/guides/theming.md
  packages/components-dev/index.html
  packages/components/core/services/theme.service.ts
  tools/public_api_guard/components/core.api.md
Labels: enhancement, breaking changes, 18.x

#377 feat(file-upload): separated validation from file-upload (#DS-2554)
  packages/components-dev/file-upload/module.ts
  packages/components-dev/file-upload/template.html
  packages/components-dev/file-upload/validation.ts
  packages/components/core/forms/validators.spec.ts
  packages/components/core/forms/validators.ts
  packages/components/file-upload/_file-upload-theme.scss
  packages/components/file-upload/examples.file-upload.md
  packages/components/file-upload/file-upload.karma-spec.ts
  packages/components/file-upload/file-upload.scss
  packages/components/file-upload/file-upload.spec.ts
  packages/components/file-upload/file-upload.ts
  packages/components/file-upload/multiple-file-upload.component.html
  packages/components/file-upload/multiple-file-upload.component.scss
  packages/components/file-upload/multiple-file-upload.component.ts
  packages/components/file-upload/single-file-upload.component.html
  packages/components/file-upload/single-file-upload.component.scss
  packages/components/file-upload/single-file-upload.component.ts
  packages/docs-examples/components/file-upload/file-upload-cva-overview/file-upload-cva-overview-example.css
  packages/docs-examples/components/file-upload/file-upload-cva-overview/file-upload-cva-overview-example.html
  packages/docs-examples/components/file-upload/file-upload-cva-overview/file-upload-cva-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-indeterminate-loading-overview/file-upload-indeterminate-loading-overview-example.css
  packages/docs-examples/components/file-upload/file-upload-indeterminate-loading-overview/file-upload-indeterminate-loading-overview-example.html
  packages/docs-examples/components/file-upload/file-upload-indeterminate-loading-overview/file-upload-indeterminate-loading-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-multiple-compact-overview/file-upload-multiple-compact-overview-example.css
  packages/docs-examples/components/file-upload/file-upload-multiple-compact-overview/file-upload-multiple-compact-overview-example.html
  packages/docs-examples/components/file-upload/file-upload-multiple-compact-overview/file-upload-multiple-compact-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-multiple-custom-text-overview/file-upload-multiple-custom-text-overview-example.css
  packages/docs-examples/components/file-upload/file-upload-multiple-custom-text-overview/file-upload-multiple-custom-text-overview-example.html
  packages/docs-examples/components/file-upload/file-upload-multiple-custom-text-overview/file-upload-multiple-custom-text-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-multiple-default-overview/file-upload-multiple-default-overview-example.css
  packages/docs-examples/components/file-upload/file-upload-multiple-default-overview/file-upload-multiple-default-overview-example.html
  packages/docs-examples/components/file-upload/file-upload-multiple-default-overview/file-upload-multiple-default-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-multiple-default-validation-reactive-forms-overview/file-upload-multiple-default-validation-reactive-forms-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-multiple-error-overview/file-upload-multiple-error-overview-example.css
  packages/docs-examples/components/file-upload/file-upload-multiple-error-overview/file-upload-multiple-error-overview-example.html
  packages/docs-examples/components/file-upload/file-upload-multiple-error-overview/file-upload-multiple-error-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-single-error-overview/file-upload-single-error-overview-example.css
  packages/docs-examples/components/file-upload/file-upload-single-error-overview/file-upload-single-error-overview-example.html
  packages/docs-examples/components/file-upload/file-upload-single-error-overview/file-upload-single-error-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-single-overview/file-upload-single-overview-example.css
  packages/docs-examples/components/file-upload/file-upload-single-overview/file-upload-single-overview-example.html
  packages/docs-examples/components/file-upload/file-upload-single-overview/file-upload-single-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-single-validation-reactive-forms-overview/file-upload-single-validation-reactive-forms-overview-example.ts
  packages/docs-examples/components/file-upload/index.ts
  packages/docs-examples/example-module.ts
  tools/public_api_guard/components/core.api.md
  tools/public_api_guard/components/file-upload.api.md
Labels: enhancement, breaking changes, 18.x
