Repository koobiq/angular-components, pull requests merged in 2024-05, with the labels that each got.

#12 feat(docs,tree): different multiple tree selection examples (#DS-2306)
  packages/components/tree/examples.tree.md
  packages/components/tree/tree.md
  packages/docs-examples/components/tree/index.ts
  packages/docs-examples/components/tree/tree-access-rights/tree-access-rights-example.css
  packages/docs-examples/components/tree/tree-access-rights/tree-access-rights-example.html
  packages/docs-examples/components/tree/tree-access-rights/tree-access-rights-example.ts
  packages/docs-examples/components/tree/tree-descendants-subcategories/tree-descendants-subcategories-example.css
  packages/docs-examples/components/tree/tree-descendants-subcategories/tree-descendants-subcategories-example.html
  packages/docs-examples/components/tree/tree-descendants-subcategories/tree-descendants-subcategories-example.ts
Labels: documentation

#16 feat(ci): added schematic for ng-add (#DS-2475)
  .github/workflows/actions/build-packages/action.yml
  .github/workflows/ci.yml
  .github/workflows/docs-next.yml
  .github/workflows/docs-stable.yml
  .github/workflows/pr-docs-preview.yml
  .github/workflows/publish.yml
  docs/guides/installation.md
  package.json
  packages/components/package.json
  packages/schematics/karma.conf.js
  packages/schematics/package.json
  packages/schematics/rollup.config.js
  packages/schematics/scripts/copy-meta-to-dist.mjs
  packages/schematics/src/collection.json
  packages/schematics/src/ng-add/index.spec.ts
  packages/schematics/src/ng-add/index.ts
  packages/schematics/src/ng-add/messages.ts
  packages/schematics/src/ng-add/schema.json
  packages/schematics/src/ng-add/schema.ts
  packages/schematics/src/utils/package-config.ts
  packages/schematics/src/utils/testing.ts
  packages/schematics/tsconfig.json
  packages/schematics/tsconfig.rollup.json
  yarn.lock
Labels: enhancement

#28 fix(textarea): title & required attributes behavior (#DS-2449)
  packages/components-dev/textarea/template.html
  packages/components/textarea/textarea.component.ts
Labels: bug

#37 fix(docs): removed unnecessary file
  packages/docs/src/styles/koobiq/default-theme/js/index.js
Labels: documentation

#34 feat(link): added css-class for active state (#DS-2436)
  packages/components/link/_link-theme.scss
Labels: enhancement

#40 fix(code-block): scroll with keyboard (#DS-2336)
  packages/components/code-block/_code-block-theme.scss
  packages/components/code-block/actionbar.component.scss
  packages/components/code-block/code-block.component.html
  packages/components/code-block/code-block.component.ts
  packages/components/code-block/code-block.scss
  packages/docs-examples/components/code-block/code-block-noborder/code-block-noborder-example.css
Labels: bug

#44 fix(docs,chore): removed dependency from nodeJS version (#DS-2476)
  package.json
  tools/api-gen/extraction/helpers.ts
  tools/api-gen/extraction/index.ts
  tools/api-gen/generate-api-docs.ts
  tools/api-gen/manifest/helpers.ts
  tools/api-gen/manifest/index.ts
  tools/api-gen/rendering/entities/categorization.ts
  tools/api-gen/rendering/entities/renderables.ts
  tools/api-gen/rendering/entities/traits.ts
  tools/api-gen/rendering/helpers.ts
  tools/api-gen/rendering/index.ts
  tools/api-gen/rendering/marked/configuration.ts
  tools/api-gen/rendering/marked/renderer.ts
  tools/api-gen/rendering/nunjucks-tags/highlight.ts
  tools/api-gen/rendering/processing.ts
  tools/api-gen/rendering/rendering.ts
  tools/api-gen/rendering/transforms/class-transforms.ts
  tools/api-gen/rendering/transforms/code-transforms.ts
  tools/api-gen/rendering/transforms/constant-transforms.ts
  tools/api-gen/rendering/transforms/enum-transforms.ts
  tools/api-gen/rendering/transforms/function-transforms.ts
  tools/api-gen/rendering/transforms/interface-transforms.ts
  tools/api-gen/rendering/transforms/jsdoc-transforms.ts
  tools/api-gen/rendering/transforms/member-transforms.ts
  tools/api-gen/rendering/transforms/module-name.ts
  tools/api-gen/rendering/transforms/params-transforms.ts
  tools/api-gen/rendering/transforms/type-alias-transforms.ts
  tools/api-gen/types/types.ts
  tools/api-gen/utils.ts
Labels: bug

#48 feat(loader-overlay): switched default filled -> transparent (#DS-2024)
  packages/components/loader-overlay/loader-overlay.component.spec.ts
  packages/components/loader-overlay/loader-overlay.component.ts
Labels: enhancement

#51 fix(docs): updated icons path (#DS-2498)
  packages/components/icon/icon.en.md
  packages/components/icon/icon.md
Labels: documentation

#50 fix(docs): layout styles override (#DS-2460)
  packages/docs-examples/components/checkbox/checkbox-overview/checkbox-overview-example.css
  packages/docs-examples/components/checkbox/pseudo-checkbox/pseudo-checkbox-example.css
Labels: bug

#39 feat(toast): toast 2.0 (#DS-2360)
  apps/docs/src/assets/stackblitz/package.json
  apps/docs/src/styles/koobiq/default-theme/_variables.scss
  apps/docs/src/styles/koobiq/default-theme/css-tokens.css
  apps/docs/src/styles/koobiq/default-theme/index.d.ts
  apps/docs/src/styles/koobiq/default-theme/js/index.js
  package.json
  packages/components-dev/toast/module.ts
  packages/components-dev/toast/module.ts.orig
  packages/components-dev/toast/styles.scss
  packages/components-dev/toast/template.html
  packages/components-dev/toast/template.html.orig
  packages/components/core/styles/theming/_components-theming.scss
  packages/components/package.json
  packages/components/toast/_toast-theme.scss
  packages/components/toast/toast-container.component.scss
  packages/components/toast/toast.component.html
  packages/components/toast/toast.component.scss
  packages/components/toast/toast.component.ts
  packages/components/toast/toast.service.ts
  packages/components/toast/toast.spec.ts
  packages/components/toast/toast.type.ts
  packages/docs-examples/components/toast/toast-actions-overview/toast-actions-overview-example.html
  packages/docs-examples/components/toast/toast-progress-bar-overview/toast-progress-bar-overview-example.html
  packages/docs-examples/components/toast/toast-report-overview/toast-report-overview-example.html
  yarn.lock
Labels: enhancement

#53 fix(splitter): Splitter isn't working with dynamic data (#DS-2487)
  packages/components/splitter/spliltter.spec.ts
  packages/components/splitter/splitter.component.ts
  packages/components/splitter/splitter.md
  packages/docs-examples/components/splitter/index.ts
  packages/docs-examples/components/splitter/splitter-dynamic-data/splitter-dynamic-data-example.css
  packages/docs-examples/components/splitter/splitter-dynamic-data/splitter-dynamic-data-example.html
  packages/docs-examples/components/splitter/splitter-dynamic-data/splitter-dynamic-data-example.ts
  tools/public_api_guard/components/splitter.api.md
Labels: bug
