Repository koobiq/angular-components, pull requests merged in 2025-03, with the labels that each got.

#525 feat(top-bar): init component (#DS-3126)
  angular.json
  apps/docs/src/app/services/documentation-items.ts
  apps/docs/src/assets/images/welcome/top-bar-dark.png
  apps/docs/src/assets/images/welcome/top-bar-light.png
  apps/docs/src/styles/_theme-kbq.scss
  package.json
  packages/components-dev/top-bar/main.ts
  packages/components-dev/top-bar/module.ts
  packages/components-dev/top-bar/styles.scss
  packages/components-dev/top-bar/template.html
  packages/components-dev/top-bar/tsconfig.app.json
  packages/components/core/styles/common/_list.scss
  packages/components/top-bar/examples.top-bar.en.md
  packages/components/top-bar/examples.top-bar.ru.md
  packages/components/top-bar/index.ts
  packages/components/top-bar/module.ts
  packages/components/top-bar/ng-package.json
  packages/components/top-bar/public-api.ts
  packages/components/top-bar/top-bar-tokens.scss
  packages/components/top-bar/top-bar.en.md
  packages/components/top-bar/top-bar.ru.md
  packages/components/top-bar/top-bar.scss
  packages/components/top-bar/top-bar.spec.ts
  packages/components/top-bar/top-bar.ts
  packages/docs-examples/components/top-bar/index.ts
  packages/docs-examples/components/top-bar/ng-package.json
  packages/docs-examples/components/top-bar/top-bar-active-breadcrumb/top-bar-active-breadcrumb-example.ts
  packages/docs-examples/components/top-bar/top-bar-breadcrumbs/top-bar-breadcrumbs-example.ts
  packages/docs-examples/components/top-bar/top-bar-overflow/top-bar-overflow-example.ts
  packages/docs-examples/components/top-bar/top-bar-overview/top-bar-overview-example.ts
  packages/docs-examples/components/top-bar/top-bar-secondary-actions-responsive/top-bar-secondary-actions-responsive-example.ts
  packages/docs-examples/components/top-bar/top-bar-secondary-actions/top-bar-secondary-actions-example.ts
  packages/docs-examples/example-module.ts
  tools/api-extractor/config.json
  tools/cspell-locales/ru.json
  tools/generate-sitemap.ts
  tools/public_api_guard/components/top-bar.api.md
  tsconfig.json
Labels: enhancement, 18.x

#560 fix(docs): manual installation guide rewritten (#DS-3415)
  docs/guides/installation.en.md
  docs/guides/installation.ru.md
Labels: bug, documentation

#564 fix(textarea): save scroll position when out of viewport (#DS-2897)
  packages/components/textarea/textarea.component.karma-spec.ts
  packages/components/textarea/textarea.component.spec.ts
  packages/components/textarea/textarea.component.ts
  tools/public_api_guard/components/textarea.api.md
Labels: help wanted

#573 fix(dropdown): dynamic submenu rendering (#DS-3454)
  packages/components/dropdown/dropdown-trigger.directive.ts
  packages/components/dropdown/dropdown.component.ts
  packages/components/dropdown/dropdown.en.md
  packages/components/dropdown/dropdown.ru.md
  packages/components/dropdown/dropdown.spec.ts
  packages/components/dropdown/dropdown.types.ts
  packages/docs-examples/components/dropdown/dropdown-recursive-template/dropdown-recursive-template-example.ts
  packages/docs-examples/components/dropdown/index.ts
  packages/docs-examples/example-module.ts
  tools/public_api_guard/components/dropdown.api.md
Labels: bug, help wanted, 18.x

#580 fix(select,tree-select): placeholder states (#DS-3390)
  packages/components/select/_select-theme.scss
  packages/components/tree-select/_tree-select-theme.scss
  packages/docs-examples/components/tag/tags-autocomplete-onpaste-off/tags-autocomplete-onpaste-off-example.ts
Labels: bug, 18.x

#584 fix(timezone): rounded timezone options (#DS-3429)
  packages/components/core/option/option-tokens.scss
  packages/components/timezone/timezone-option-tokens.scss
Labels: bug, 18.x

#591 chore(docs): upd docs after tokens update (#DS-3467)
  apps/docs/src/assets/stackblitz/package.json
  apps/docs/src/styles/koobiq/default-theme/_palette.scss
  apps/docs/src/styles/koobiq/default-theme/_variables.scss
  apps/docs/src/styles/koobiq/default-theme/css-tokens-dark.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-light.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens.css
  apps/docs/src/styles/koobiq/default-theme/js/index.d.ts
  apps/docs/src/styles/koobiq/default-theme/js/index.js
  apps/docs/src/styles/koobiq/default-theme/js/index.mjs
  docs/guides/design-tokens/colors.md
  docs/guides/design-tokens/palette.md
  package.json
  packages/components/package.json
  yarn.lock
Labels: documentation

#594 chore(deps): updated @koobiq/icons to 9.3.1 (#DS-3446)
  apps/docs/src/assets/stackblitz/package.json
  package.json
  packages/components/package.json
  yarn.lock
Labels: dependencies

#585 fix(radio): vertical gap and size (#DS-3490)
  packages/components/core/styles/common/_tokens.scss
  packages/components/radio/radio-tokens.scss
  packages/components/radio/radio.scss
Labels: bug

#588 fix(list, tree): set focus to selected option (#DS-3422)
  packages/components/list/list-selection.component.spec.ts
  packages/components/list/list-selection.component.ts
  packages/components/tree/tree-selection.component.spec.ts
  packages/components/tree/tree-selection.component.ts
Labels: bug

#599 fix(top-bar): adjusted padding & correct CSS var assignment
  packages/components/top-bar/top-bar-tokens.scss
  packages/components/top-bar/top-bar.scss
Labels: bug

#604 fix(popover): show on ENTER keydown (#DS-3303)
  packages/components-dev/button-toggle/module.ts
  packages/components-dev/button-toggle/template.html
  packages/components/core/pop-up/pop-up-trigger.ts
Labels: bug

#608 fix(form-field, select, tree-select): legacy validate directive selector (#DS-3515)
  packages/components/form-field/_form-field-theme.scss
  packages/components/form-field/validate.directive.ts
  packages/components/select/_select-theme.scss
  packages/components/tree-select/_tree-select-theme.scss
  tools/public_api_guard/components/form-field.api.md
Labels: bug

#611 feat(breadcrumbs): negative margin (#DS-3457)
  packages/components/breadcrumbs/__snapshots__/breadcrumbs.spec.ts.snap
  packages/components/breadcrumbs/breadcrumbs-tokens.scss
  packages/components/breadcrumbs/breadcrumbs.en.md
  packages/components/breadcrumbs/breadcrumbs.html
  packages/components/breadcrumbs/breadcrumbs.ru.md
  packages/components/breadcrumbs/breadcrumbs.scss
  packages/components/breadcrumbs/breadcrumbs.spec.ts
  packages/components/breadcrumbs/breadcrumbs.ts
  tools/public_api_guard/components/breadcrumbs.api.md
Labels: enhancement

#617 chore: updated deps @koobiq/icons to 9.4.0 (#DS-3560)
  apps/docs/src/assets/stackblitz/package.json
  package.json
  packages/components/package.json
  yarn.lock
Labels: dependencies

#616 feat(docs): note required @radix-ng/primitives package (#DS-3494)
  packages/components/accordion/accordion.en.md
  packages/components/accordion/accordion.ru.md
  packages/components/breadcrumbs/breadcrumbs.en.md
  packages/components/breadcrumbs/breadcrumbs.ru.md
Labels: documentation

#615 fix(progress-spinner): remove gap if ng-content is not provided (#DS-3568)
  packages/components/progress-spinner/progress-spinner.scss
Labels: bug

#614 fix(button): animation in progress state (#DS-3563)
  packages/components-dev/button/styles.scss
  packages/components/button/button.scss
Labels: bug

#619 feat(overflow-items): hide items in the middle
  packages/components-dev/overflow-items/module.ts
  packages/components/breadcrumbs/breadcrumbs.html
  packages/components/overflow-items/overflow-items.en.md
  packages/components/overflow-items/overflow-items.ru.md
  packages/components/overflow-items/overflow-items.ts
  packages/docs-examples/components/overflow-items/index.ts
  packages/docs-examples/components/overflow-items/overflow-items-result-offset/overflow-items-result-offset-example.ts
  tools/public_api_guard/components/overflow-items.api.md
Labels: enhancement

#625 chore: locked firebase-tools version in ci
  .github/workflows/pr-docs-preview.yml
Labels: bug

#622 feat(scrollbar): updated thumb color states (#DS-2866)
  packages/components/core/styles/theming/scrollbar-tokens.scss
  packages/components/scrollbar/scrollbar-tokens.scss
Labels: enhancement, 18.x
