Repository koobiq/angular-components, pull requests merged in 2025-04, with the labels that each got.

#631 fix(docs): api tab in tag component (#DS-3524)
  apps/docs/src/app/services/documentation-items.ts
Labels: bug, documentation

#621 feat(overflow-items): hide items in the middle
  packages/components-dev/overflow-items/module.ts
  packages/components/overflow-items/overflow-items.en.md
  packages/components/overflow-items/overflow-items.karma-spec.ts
  packages/components/overflow-items/overflow-items.ru.md
  packages/components/overflow-items/overflow-items.ts
  packages/docs-examples/components/overflow-items/index.ts
  packages/docs-examples/components/overflow-items/overflow-items-overview/overflow-items-overview-example.ts
  packages/docs-examples/components/overflow-items/overflow-items-with-order/overflow-items-with-order-example.ts
  packages/docs-examples/example-module.ts
  tools/public_api_guard/components/overflow-items.api.md
Labels: enhancement

#629 feat(schematics): add empty-state schematics for attribute replacement (#DS-3507)
  packages/schematics/src/collection.json
  packages/schematics/src/migrations/empty-state-size-attr/README.md
  packages/schematics/src/migrations/empty-state-size-attr/__snapshots__/index.spec.ts.snap
  packages/schematics/src/migrations/empty-state-size-attr/index.spec.ts
  packages/schematics/src/migrations/empty-state-size-attr/index.ts
  packages/schematics/src/migrations/empty-state-size-attr/schema.json
  packages/schematics/src/migrations/empty-state-size-attr/schema.ts
Labels: enhancement

#643 feat(schematics): added loader-overlay migration new property schematic (#DS-3507)
  packages/schematics/src/collection.json
  packages/schematics/src/migrations/loader-overlay-size-attr/README.md
  packages/schematics/src/migrations/loader-overlay-size-attr/__snapshots__/index.spec.ts.snap
  packages/schematics/src/migrations/loader-overlay-size-attr/index.spec.ts
  packages/schematics/src/migrations/loader-overlay-size-attr/index.ts
  packages/schematics/src/migrations/loader-overlay-size-attr/schema.json
  packages/schematics/src/migrations/loader-overlay-size-attr/schema.ts
Labels: enhancement

#623 feat(empty-state)!: update empty-state sizes (#DS-3507)
  apps/docs/src/app/components/icons-viewer/icons-viewer.template.html
  packages/components-dev/empty-state/module.ts
  packages/components-dev/empty-state/template.html
  packages/components/empty-state/_empty-state-theme.scss
  packages/components/empty-state/empty-state-tokens.scss
  packages/components/empty-state/empty-state.component.spec.ts
  packages/components/empty-state/empty-state.component.ts
  packages/components/empty-state/empty-state.ru.md
  packages/components/empty-state/empty-state.scss
  packages/docs-examples/components/empty-state/empty-state-big/empty-state-big-example.ts
  packages/docs-examples/components/empty-state/empty-state-content/empty-state-content-example.ts
  packages/docs-examples/components/empty-state/empty-state-size/empty-state-size-example.ts
  packages/docs-examples/components/empty-state/index.ts
  packages/docs-examples/example-module.ts
  packages/schematics/src/collection.json
  packages/schematics/src/migrations/empty-state-size-attr/README.md
  packages/schematics/src/migrations/empty-state-size-attr/__snapshots__/index.spec.ts.snap
  packages/schematics/src/migrations/empty-state-size-attr/index.spec.ts
  packages/schematics/src/migrations/empty-state-size-attr/index.ts
  packages/schematics/src/migrations/empty-state-size-attr/schema.json
  packages/schematics/src/migrations/empty-state-size-attr/schema.ts
  tools/api-extractor/config.json
  tools/public_api_guard/components/empty-state.api.md
Labels: enhancement, breaking changes

#624 feat(loader-overlay)!: update loader-overlay sizes (#DS-3507)
  packages/components-dev/loader-overlay/module.ts
  packages/components-dev/loader-overlay/template.html
  packages/components/loader-overlay/__snapshots__/loader-overlay.component.spec.ts.snap
  packages/components/loader-overlay/_loader-overlay-theme.scss
  packages/components/loader-overlay/loader-overlay-tokens.scss
  packages/components/loader-overlay/loader-overlay.component.spec.ts
  packages/components/loader-overlay/loader-overlay.component.ts
  packages/components/loader-overlay/loader-overlay.ru.md
  packages/components/loader-overlay/loader-overlay.scss
  packages/docs-examples/components/loader-overlay/index.ts
  packages/docs-examples/components/loader-overlay/loader-overlay-default/loader-overlay-default-example.ts
  packages/docs-examples/components/loader-overlay/loader-overlay-fixed-top/loader-overlay-fixed-top-example.ts
  packages/docs-examples/components/loader-overlay/loader-overlay-large/loader-overlay-large-example.ts
  packages/docs-examples/components/loader-overlay/loader-overlay-overview/loader-overlay-overview-example.ts
  packages/docs-examples/components/loader-overlay/loader-overlay-size/loader-overlay-size-example.ts
  packages/docs-examples/example-module.ts
  packages/schematics/src/collection.json
  packages/schematics/src/migrations/loader-overlay-size-attr/README.md
  packages/schematics/src/migrations/loader-overlay-size-attr/__snapshots__/index.spec.ts.snap
  packages/schematics/src/migrations/loader-overlay-size-attr/index.spec.ts
  packages/schematics/src/migrations/loader-overlay-size-attr/index.ts
  packages/schematics/src/migrations/loader-overlay-size-attr/schema.json
  packages/schematics/src/migrations/loader-overlay-size-attr/schema.ts
  tools/public_api_guard/components/loader-overlay.api.md
Labels: enhancement, breaking changes

#648 fix(alert): align info variant with design (#DS-3602)
  packages/components/alert/_alert-theme.scss
  packages/components/alert/alert-tokens.scss
  packages/components/alert/alert.component.ts
  packages/docs-examples/components/alert/alert-status/alert-status-example.html
Labels: bug

#652 chore(docs): added docs feedback callout (#DS-3653)
  apps/docs/src/app/components/component-viewer/component-overview.template.html
  apps/docs/src/app/components/component-viewer/component-viewer.component.ts
  apps/docs/src/app/components/component-viewer/component-viewer.scss
  apps/docs/src/app/components/design-tokens-viewers/tokens-overview.ts
  apps/docs/src/app/components/live-example-viewer/docs-live-example-viewer.scss
  apps/docs/src/app/components/live-example/docs-live-example.ts
  packages/components/markdown/markdown.scss
Labels: documentation

#655 fix(filter-bar): size of label in date pipe (#DS-3643)
  packages/components-dev/filter-bar/module.ts
  packages/components-dev/filter-bar/template.html
  packages/components/core/pop-up/pop-up-trigger.ts
  packages/components/filter-bar/pipes/pipe-date.html
  packages/components/filter-bar/pipes/pipe-date.scss
  packages/components/filter-bar/pipes/pipe-datetime.html
Labels: bug

#654 feat(docs): added сore section (#DS-3340)
  apps/docs/src/app/services/documentation-items.ts
  packages/components/core/core.en.md
  packages/components/core/core.ru.md
  tools/cspell-locales/ru.json
  tools/generate-sitemap.ts
Labels: documentation

#657 fix(radio, toggle): multiline support (#DS-3538)
  packages/components-dev/radio/module.ts
  packages/components-dev/radio/template.html
  packages/components-dev/toggle/main.ts
  packages/components-dev/toggle/module.ts
  packages/components-dev/toggle/template.html
  packages/components/radio/radio.en.md
  packages/components/radio/radio.ru.md
  packages/components/radio/radio.scss
  packages/components/toggle/toggle.ru.md
  packages/docs-examples/components/radio/index.ts
  packages/docs-examples/components/radio/radio-group/radio-group-example.ts
  packages/docs-examples/components/radio/radio-multiline/radio-multiline-example.ts
  packages/docs-examples/components/radio/radio-size/radio-size-example.ts
  packages/docs-examples/components/radio/radio-style/radio-style-example.ts
  packages/docs-examples/components/toggle/index.ts
  packages/docs-examples/components/toggle/toggle-multiline/toggle-multiline-example.ts
  packages/docs-examples/example-module.ts
Labels: bug

#658 fix(breadcrumbs): fixed error on component import (#DS-3523)
  docs/guides/installation.en.md
  docs/guides/installation.ru.md
  package.json
  packages/components/package.json
  yarn.lock
Labels: bug

#661 chore(docs): removed filter of redundant class members (#DS-3657)
  tools/api-gen/extraction/helpers.ts
Labels: documentation

#650 feat(toggle): indeterminate state (#DS-3483)
  packages/components-dev/toggle/module.ts
  packages/components-dev/toggle/template.html
  packages/components/checkbox/checkbox.ts
  packages/components/core/animation/animation.ts
  packages/components/core/common-behaviors/checkbox.ts
  packages/components/core/common-behaviors/index.ts
  packages/components/toggle/_toggle-theme.scss
  packages/components/toggle/toggle-tokens.scss
  packages/components/toggle/toggle.component.html
  packages/components/toggle/toggle.component.spec.ts
  packages/components/toggle/toggle.component.ts
  packages/components/toggle/toggle.en.md
  packages/components/toggle/toggle.ru.md
  packages/components/toggle/toggle.scss
  packages/docs-examples/components/toggle/index.ts
  packages/docs-examples/components/toggle/toggle-indeterminate/toggle-indeterminate-example.ts
  packages/docs-examples/example-module.ts
  tools/public_api_guard/components/checkbox.api.md
  tools/public_api_guard/components/core.api.md
  tools/public_api_guard/components/toggle.api.md
Labels: enhancement

#662 feat(docs): added "new" section badge in sidenav (#DS-3386)
  apps/docs/src/app/components/sidenav/sidenav.component.html
  apps/docs/src/app/components/sidenav/sidenav.component.ts
  apps/docs/src/app/services/documentation-items.ts
Labels: documentation

#675 feat(toggle): added click on enter (#DS-3656)
  packages/components/toggle/toggle.component.html
Labels: enhancement

#674 fix(docs): docsearch button keyboard focus (#DS-3010)
  apps/docs/src/app/components/navbar/navbar.scss
  apps/docs/src/app/components/navbar/navbar.template.html
  apps/docs/src/styles/_docsearch.scss
Labels: documentation

#682 fix(file-upload): removed infinite change detection (#DS-3493)
  packages/components/file-upload/examples.file-upload.en.md
  packages/components/file-upload/examples.file-upload.ru.md
  packages/components/file-upload/file-upload.karma-spec.ts
  packages/components/file-upload/file-upload.spec.ts
  packages/components/file-upload/multiple-file-upload.component.ts
  packages/components/file-upload/single-file-upload.component.ts
  packages/docs-examples/components/file-upload/file-upload-single-with-signal/file-upload-single-with-signal-example.ts
  packages/docs-examples/components/file-upload/index.ts
Labels: bug

#683 chore(file-upload): jsdocs & dev examples
  packages/components-dev/file-upload/main.ts
  packages/components-dev/file-upload/module.ts
  packages/components-dev/file-upload/template.html
  packages/components/file-upload/examples.file-upload.en.md
  packages/components/file-upload/examples.file-upload.ru.md
  packages/components/file-upload/file-drop.ts
  packages/components/file-upload/file-upload.karma-spec.ts
  packages/components/file-upload/file-upload.ts
  packages/components/file-upload/multiple-file-upload.component.ts
  packages/components/file-upload/single-file-upload.component.ts
  packages/docs-examples/example-module.ts
  tools/public_api_guard/components/file-upload.api.md
Labels: enhancement

#687 fix(file-upload): sync events order on files changes (#DS-3451)
  packages/components/file-upload/multiple-file-upload.component.ts
  packages/components/file-upload/single-file-upload.component.ts
Labels: bug

#691 fix(tags): sync placeholder padding with design (#DS-3484)
  packages/components/tags/tag-list.scss
Labels: bug

#702 fix(textarea): aligned paddings with design (#DS-3720)
  packages/components/textarea/textarea-tokens.scss
Labels: bug

#707 fix(checkbox): removed bottom margin (#DS-3723)
  packages/components/checkbox/checkbox-tokens.scss
  packages/components/checkbox/checkbox.scss
Labels: bug

#703 fix(list): focused option border radius (#DS-3707)
  packages/components/list/_list-theme.scss
  packages/components/list/list.scss
Labels: bug

#710 fix(tags): mark tag-list pristine on init (#DS-3669)
  packages/components/tags/tag-list.component.spec.ts
  packages/components/tags/tag-list.component.ts
Labels: bug

#706 fix(file-upload): corrected file add emit on click (#DS-3451)
  packages/components/file-upload/file-upload.karma-spec.ts
  packages/components/file-upload/file-upload.spec.ts
  packages/components/file-upload/multiple-file-upload.component.ts
  packages/components/file-upload/single-file-upload.component.ts
Labels: bug

#714 fix(toast): adjust margin when used custom position (#DS-3370)
  packages/components-dev/toast/main.ts
  packages/components-dev/toast/module.ts
  packages/components/toast/toast-container.component.scss
  packages/components/toast/toast-tokens.scss
  packages/components/toast/toast.service.ts
Labels: bug

#715 chore(toast): refactoring (#DS-3370)
  packages/components-dev/toast/main.ts
  packages/components/toast/toast.ru.md
  packages/components/toast/toast.service.ts
  packages/components/toast/toast.type.ts
  tools/public_api_guard/components/toast.api.md
Labels: enhancement
