Repository koobiq/angular-components, pull requests merged in 2025-06, with the labels that each got.

#800 chore(deps): updated @koobiq/icons to 10.1.0 (#DS-3797)
  apps/docs/src/assets/stackblitz/package.json
  package.json
  packages/components/package.json
  yarn.lock
Labels: dependencies

#806 fix(file-upload): disabled state colors (#DS-3824)
  packages/components/file-upload/_file-upload-theme.scss
  packages/components/file-upload/file-upload-tokens.scss
  packages/components/file-upload/multiple-file-upload.component.html
  packages/components/file-upload/single-file-upload.component.html
Labels: bug

#802 fix(form-field,experimental): selectors nesting (#DS-3787)
  packages/components-experimental/form-field/_form-field-theme.scss
  packages/components/form-field/_form-field-theme.scss
  packages/components/form-field/form-field.scss
  packages/docs-examples/components/form-field/form-field-password-overview/form-field-password-overview-example.ts
Labels: bug

#799 chore(dev): added ssr mode (#DS-3828)
  .github/dependabot.yml
  angular.json
  docs/guides/09-ssr-dev.md
  package.json
  packages/components-dev/breadcrumbs/main.ts
  packages/components-dev/ssr/app.config.server.ts
  packages/components-dev/ssr/main.server.ts
  packages/components-dev/ssr/main.ts
  packages/components-dev/ssr/server.ts
  packages/components-dev/ssr/tsconfig.app.json
  tools/cspell-locales/en.json
  yarn.lock
Labels: enhancement

#815 chore(docs): added preview images (#DS-3811)
  apps/docs/src/app/services/documentation-items.ts
  apps/docs/src/assets/images/welcome/formatter-filesize-dark.png
  apps/docs/src/assets/images/welcome/formatter-filesize-light.png
  apps/docs/src/assets/images/welcome/sidebar-dark.png
  apps/docs/src/assets/images/welcome/sidebar-light.png
Labels: documentation

#840 chore: updated dependabot schedule interval to monthly
  .github/dependabot.yml
Labels: enhancement

#829 chore: removed unused karma dependencies and added typecheck
  .github/dependabot.yml
  angular.json
  karma.conf.js
  karma.conf.ts
  package.json
  packages/components/karma.conf.ts
  yarn.lock
Labels: enhancement

#825 fix(file-upload): layout improvements (#DS-3714)
  packages/components-dev/file-upload/module.ts
  packages/components/ellipsis-center/ellipsis-center.directive.ts
  packages/components/file-upload/_file-upload-theme.scss
  packages/components/file-upload/file-upload-tokens.scss
  packages/components/file-upload/multiple-file-upload.component.html
  packages/components/file-upload/multiple-file-upload.component.scss
  packages/components/file-upload/multiple-file-upload.component.ts
  packages/components/file-upload/single-file-upload.component.html
  packages/docs-examples/components/file-upload/file-upload-multiple-default-validation-reactive-forms-overview/file-upload-multiple-default-validation-reactive-forms-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-multiple-error-overview/file-upload-multiple-error-overview-example.ts
  tools/public_api_guard/components/file-upload.api.md
Labels: bug

#857 fix(docs): build warning (#DS-3823)
  apps/docs/src/app/components/navbar/navbar.template.html
Labels: bug

#871 feat(docs): v17 -> v18 migration guide (#DS-3848)
  apps/docs/src/app/services/documentation-items.ts
  docs/guides/migration.en.md
  docs/guides/migration.ru.md
  tools/cspell-locales/ru.json
Labels: documentation

#879 fix(top-bar): properly align end container (#DS-3886)
  packages/components/overflow-items/overflow-items.ts
  packages/components/top-bar/top-bar.scss
  packages/docs-examples/components/top-bar/top-bar-actions/top-bar-actions-example.ts
  packages/docs-examples/components/top-bar/top-bar-breadcrumbs-adaptive/top-bar-breadcrumbs-adaptive-example.ts
  packages/docs-examples/components/top-bar/top-bar-breadcrumbs/top-bar-breadcrumbs-example.ts
  packages/docs-examples/components/top-bar/top-bar-overflow/top-bar-overflow-example.ts
  packages/docs-examples/components/top-bar/top-bar-overview/top-bar-overview-example.ts
  packages/docs-examples/components/top-bar/top-bar-title-counter-adaptive/top-bar-title-counter-adaptive-example.ts
  packages/docs-examples/components/top-bar/top-bar-title-counter/top-bar-title-counter-example.ts
  packages/docs-examples/example-module.ts
Labels: bug
