Repository koobiq/angular-components, pull requests merged in 2025-05, with the labels that each got.

#720 feat(docs): default icon color in modal (#DS-3747)
  apps/docs/src/app/components/icons-viewer/icon-preview-modal/icon-preview-modal.component.ts
Labels: documentation

#721 chore(docs): code-snippet refactoring
  angular.json
  apps/docs/src/app/components/code-snippet/code-snippet.ts
  apps/docs/src/app/components/icons-viewer/icon-preview-modal/icon-preview-modal.component.ts
  apps/docs/src/app/components/icons-viewer/icon-preview-modal/icon-preview-modal.template.html
  apps/docs/src/app/components/live-example/docs-live-example.ts
  apps/docs/src/main.scss
  apps/docs/src/styles/_code-snippet.scss
  apps/docs/src/styles/_design-tokens.scss
  docs/guides/design-tokens/border-radius.md
  docs/guides/design-tokens/colors.md
  docs/guides/design-tokens/palette.md
  docs/guides/design-tokens/semantic-palette.md
  docs/guides/design-tokens/shadows.md
  docs/guides/design-tokens/sizes.md
  packages/components/core/styles/typography/typography.en.md
  packages/components/core/styles/typography/typography.ru.md
  tools/tokens/docs/templates.js
Labels: documentation

#718 fix(select, tree-select): state color (#DS-3751)
  packages/components/select/select.component.ts
  packages/components/tree-select/tree-select.component.ts
  tools/public_api_guard/components/select.api.md
  tools/public_api_guard/components/tree-select.api.md
Labels: bug

#734 chore(docs): updated sitemap
  apps/docs/src/sitemap.xml
  tools/generate-sitemap.ts
Labels: documentation

#735 fix(docs): upd article layout (#DS-3706)
  apps/docs/src/app/components/component-viewer/component-viewer.scss
Labels: documentation

#737 fix(file-upload): show icon when file is selected (#DS-3183)
  packages/components-dev/file-upload/module.ts
  packages/components-dev/file-upload/template.html
  packages/docs-examples/components/file-upload/file-upload-indeterminate-loading-overview/file-upload-indeterminate-loading-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-multiple-compact-overview/file-upload-multiple-compact-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-multiple-custom-text-overview/file-upload-multiple-custom-text-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-multiple-default-validation-reactive-forms-overview/file-upload-multiple-default-validation-reactive-forms-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-multiple-error-overview/file-upload-multiple-error-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-multiple-required-reactive-validation/file-upload-multiple-required-reactive-validation-example.ts
  packages/docs-examples/components/file-upload/file-upload-single-error-overview/file-upload-single-error-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-single-overview/file-upload-single-overview-example.ts
  packages/docs-examples/components/file-upload/file-upload-single-required-reactive-validation/file-upload-single-required-reactive-validation-example.ts
  packages/docs-examples/components/file-upload/file-upload-single-validation-reactive-forms-overview/file-upload-single-validation-reactive-forms-overview-example.ts
Labels: documentation

#767 fix(file-upload): added single-file-upload min-height (#DS-3775)
  packages/components/file-upload/file-upload-tokens.scss
  packages/components/file-upload/single-file-upload.component.scss
Labels: bug

#781 fix(filter-bar): emit one event when all options are selected (#DS-3771)
  packages/components/filter-bar/pipes/pipe-multi-select.ts
  packages/docs-examples/components/filter-bar/filter-bar-master-checkbox/filter-bar-master-checkbox-example.ts
Labels: bug

#779 fix(dropdown): nested item trigger icon color (#DS-3715)
  packages/components/dropdown/dropdown-item.component.ts
  packages/components/dropdown/dropdown-item.html
  tools/public_api_guard/components/dropdown.api.md
Labels: bug

#784 feat(docs,popover): added example for arrow adjustments (#DS-3260)
  packages/components-dev/popover/module.ts
  packages/components/popover/popover.ru.md
  packages/docs-examples/components/popover/index.ts
  packages/docs-examples/components/popover/popover-arrow-and-offset/popover-arrow-and-offset-example.ts
  packages/docs-examples/components/popover/popover-arrowless/popover-arrowless-example.ts
  packages/docs-examples/example-module.ts
Labels: documentation

#786 chore(dev): updated theme-toggle component
  packages/components-dev/theme-toggle.ts
Labels: enhancement

#766 feat(core): update filesize formatter & docs (#DS-3357)
  angular.json
  apps/docs/src/app/services/documentation-items.ts
  apps/docs/src/sitemap.xml
  package.json
  packages/components-dev/filesize-formatter/main.ts
  packages/components-dev/filesize-formatter/module.ts
  packages/components-dev/filesize-formatter/styles.scss
  packages/components-dev/filesize-formatter/template.html
  packages/components-dev/filesize-formatter/tsconfig.app.json
  packages/components/core/formatters/filesize/config.ts
  packages/components/core/formatters/filesize/filesize-formatter.en.md
  packages/components/core/formatters/filesize/filesize-formatter.ru.md
  packages/components/core/formatters/filesize/formatter.spec.ts
  packages/components/core/formatters/filesize/formatter.ts
  packages/components/core/formatters/filesize/index.ts
  packages/components/core/formatters/filesize/size.ts
  packages/components/core/formatters/index.ts
  packages/components/core/locales/formatters.ts
  packages/components/core/utils/data-size/config.ts
  packages/components/core/utils/data-size/data-size.pipe.ts
  packages/components/core/utils/data-size/size.spec.ts
  packages/components/core/utils/data-size/size.ts
  packages/components/core/utils/public-api.ts
  packages/docs-examples/components/filesize-formatter/filesize-formatter-overview/filesize-formatter-overview-example.ts
  packages/docs-examples/components/filesize-formatter/filesize-formatter-table-number/filesize-formatter-table-number-example.ts
  packages/docs-examples/components/filesize-formatter/index.ts
  packages/docs-examples/components/filesize-formatter/ng-package.json
  packages/docs-examples/example-module.ts
  tools/generate-sitemap.ts
  tools/public_api_guard/components/core.api.md
Labels: enhancement

#796 feat(formatter): use thin-space for groups (#DS-3087)
  packages/components-dev/all/module.ts
  packages/components-dev/all/template.html
  packages/components-dev/form-field/module.ts
  packages/components-dev/form-field/template.html
  packages/components-dev/input/module.ts
  packages/components-dev/input/template.html
  packages/components-dev/number-formatter/module.ts
  packages/components-dev/number-formatter/template.html
  packages/components/core/formatters/number/formatter.ts
  packages/components/core/formatters/number/number-formatter.ru.md
  packages/components/core/locales/formatters.ts
  packages/components/core/locales/types.ts
  packages/components/input/input-number.spec.ts
  packages/components/input/input-number.ts
  packages/components/input/input.ru.md
  packages/docs-examples/components/filesize-formatter/filesize-formatter-overview/filesize-formatter-overview-example.ts
  packages/docs-examples/components/input/input-number-overview/input-number-overview-example.ts
  packages/docs-examples/components/number-formatter/number-formatter-overview/number-formatter-overview-example.html
  packages/docs-examples/components/number-formatter/number-formatter-overview/number-formatter-overview-example.ts
  tools/public_api_guard/components/core.api.md
  tools/public_api_guard/components/input.api.md
Labels: enhancement
