Repository koobiq/angular-components, pull requests merged in 2025-07, with the labels that each got.

#884 feat(toggle): upd checked/indeterminate disabled colors (#DS-3861)
  apps/docs/scripts/build-tokens.js
  apps/docs/src/styles/koobiq/default-theme/_palette.scss
  apps/docs/src/styles/koobiq/default-theme/_variables.scss
  apps/docs/src/styles/koobiq/default-theme/css-tokens-dark.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens-light.css
  apps/docs/src/styles/koobiq/default-theme/css-tokens.css
  apps/docs/src/styles/koobiq/default-theme/js/index.d.ts
  apps/docs/src/styles/koobiq/default-theme/js/index.js
  apps/docs/src/styles/koobiq/default-theme/js/index.mjs
  packages/components/toggle/_toggle-theme.scss
  packages/components/toggle/toggle-tokens.scss
  packages/components/toggle/toggle.scss
Labels: enhancement

#876 feat(input): stepper redesign (#DS-3678)
  packages/components-experimental/form-field/form-field.scss
  packages/components-experimental/form-field/stepper.scss
  packages/components-experimental/form-field/stepper.ts
  packages/components/form-field/form-field.scss
  packages/components/form-field/stepper.scss
  packages/components/form-field/stepper.ts
Labels: enhancement

#893 feat(docs): upd migration section text (#DS-3934)
  docs/guides/migration.en.md
  docs/guides/migration.ru.md
Labels: documentation

#896 fix(file-upload): error on last file deleted (#DS-3935)
  packages/components/file-upload/file-upload.spec.ts
  packages/components/file-upload/multiple-file-upload.component.ts
Labels: bug

#895 fix(ellipsis-center,file-upload): name column width recalculation (#DS-3936)
  packages/components/ellipsis-center/ellipsis-center.directive.spec.ts
  packages/components/ellipsis-center/ellipsis-center.directive.ts
  tools/api-extractor/config.json
  tools/public_api_guard/components/ellipsis-center.api.md
Labels: bug

#907 fix(code-block): viewLess button event handling on enter keydown (#DS-3860)
  packages/components/code-block/code-block.html
  packages/components/code-block/code-block.spec.ts
  packages/components/code-block/code-block.ts
  tools/public_api_guard/components/code-block.api.md
Labels: bug

#913 fix(scrollbar): ssr compatability error (#DS-3854)
  packages/components/scrollbar/scrollbar.component.spec.ts
  packages/components/scrollbar/scrollbar.component.ts
Labels: bug

#921 fix(docs): added form-field for sitemap (#DS-3995)
  apps/docs/src/sitemap.xml
  tools/generate-sitemap.ts
Labels: bug

#924 chore: updated deps @koobiq/icons to 10.5.1 (#DS-4005)
  apps/docs/src/assets/stackblitz/package.json
  package.json
  yarn.lock
Labels: dependencies

#926 fix(input): adjust password focus for validation (#DS-3965)
  packages/components/input/input-password.spec.ts
  packages/components/input/input-password.ts
Labels: bug

#933 fix(filter-bar): open filter after reset (#DS-4000)
  packages/components/filter-bar/filter-bar.ts
  packages/components/filter-bar/filter-bar.types.ts
  packages/components/filter-bar/filter-reset.ts
  packages/components/filter-bar/pipes/base-pipe.ts
  packages/docs-examples/components/filter-bar/filter-bar-overview/filter-bar-overview-example.ts
  packages/docs-examples/components/filter-bar/filter-bar-required/filter-bar-required-example.ts
  packages/docs-examples/components/filter-bar/filter-bar-saved-filters/filter-bar-saved-filters-example.ts
  tools/public_api_guard/components/filter-bar.api.md
Labels: bug

#936 fix(filter-bar): filter list is not displayed (#DS-4035)
  packages/components/filter-bar/filters.ts
Labels: bug

#940 fix(modal): removed form submission on "X" button (#DS-3792)
  packages/components/modal/modal.component.html
  packages/components/modal/modal.directive.ts
Labels: bug

#941 fix(input): properly set cursor position on number removal (#DS-3237)
  packages/components/input/input-number.ts
Labels: bug
