Repository koobiq/angular-components, pull requests merged in 2025-08, with the labels that each got.

#960 feat(select): default panelMinWidth set to 200px (#DS-4066)
  packages/components-dev/select/module.ts
  packages/components/select/select.component.ts
  packages/components/select/select.en.md
  packages/components/select/select.ru.md
  packages/docs-examples/components/select/index.ts
  packages/docs-examples/components/select/select-with-panel-min-width/select-with-panel-min-width-example.ts
  packages/docs-examples/example-module.ts
  tools/public_api_guard/components/select.api.md
Labels: enhancement

#965 fix(select,tree-select): set disabled state at proper step (#DS-4071)
  packages/components/select/select.component.ts
  packages/components/tree-select/tree-select.component.ts
Labels: bug

#981 fix(input): invalid state for kbqInputPassword (#DS-4050)
  packages/components/form-field/__snapshots__/form-field.spec.ts.snap
  packages/components/form-field/form-field.ts
  packages/components/form-field/password-hint.ts
  packages/components/form-field/reactive-password-hint.ts
  packages/components/select/select.component.spec.ts
  tools/public_api_guard/components/form-field.api.md
Labels: bug

#967 feat(clamped-text): init component (#DS-4051)
  .github/CODEOWNERS
  angular.json
  apps/docs/src/app/structure.ts
  apps/docs/src/assets/images/welcome/clamped-text-dark.png
  apps/docs/src/assets/images/welcome/clamped-text-light.png
  apps/docs/src/sitemap.xml
  package.json
  packages/components-dev/clamped-text/main.ts
  packages/components-dev/clamped-text/module.ts
  packages/components-dev/clamped-text/styles.scss
  packages/components-dev/clamped-text/template.html
  packages/components-dev/clamped-text/tsconfig.app.json
  packages/components/clamped-text/clamped-text.en.md
  packages/components/clamped-text/clamped-text.karma-spec.ts
  packages/components/clamped-text/clamped-text.ru.md
  packages/components/clamped-text/clamped-text.scss
  packages/components/clamped-text/clamped-text.ts
  packages/components/clamped-text/constants.ts
  packages/components/clamped-text/index.ts
  packages/components/clamped-text/module.ts
  packages/components/clamped-text/ng-package.json
  packages/components/core/locales/en-US.ts
  packages/components/core/locales/es-LA.ts
  packages/components/core/locales/fa-IR.ts
  packages/components/core/locales/pt-BR.ts
  packages/components/core/locales/ru-RU.ts
  packages/components/core/locales/tk-TM.ts
  packages/components/core/locales/types.ts
  packages/components/core/locales/zh-CN.ts
  packages/docs-examples/components/clamped-text/clamped-text-overview/clamped-text-overview-example.ts
  packages/docs-examples/components/clamped-text/index.ts
  packages/docs-examples/components/clamped-text/ng-package.json
  packages/docs-examples/example-module.ts
  tools/api-extractor/config.json
  tools/public_api_guard/components/clamped-text.api.md
  tools/public_api_guard/components/core.api.md
  tsconfig.json
Labels: enhancement

#988 chore(docs): added core preview (#DS-3832)
  apps/docs/src/app/structure.ts
  apps/docs/src/assets/images/welcome/core-dark.png
  apps/docs/src/assets/images/welcome/core-light.png
Labels: documentation

#985 fix(filter-bar): emit onClosePipe event (#DS-4097)
  packages/components/filter-bar/pipes/pipe-date.ts
  packages/components/filter-bar/pipes/pipe-datetime.ts
  packages/components/filter-bar/pipes/pipe-multi-select.ts
  packages/components/filter-bar/pipes/pipe-multi-tree-select.ts
  packages/components/filter-bar/pipes/pipe-select.ts
  packages/components/filter-bar/pipes/pipe-text.ts
  packages/components/filter-bar/pipes/pipe-tree-select.ts
  tools/public_api_guard/components/filter-bar.api.md
Labels: bug

#993 fix(filter-bar): console.error in [KbqPipeMinWidth] (#DS-4099)
  packages/components/filter-bar/pipes/base-pipe.ts
Labels: bug

#992 fix(file-upload): lowered hint color specificity order (#DS-4114)
  packages/components/file-upload/_file-upload-theme.scss
Labels: bug

#994 fix(datepicker): console error when using DatePicker (#DS-4100)
  packages/components/datepicker/datepicker-input.directive.ts
  tools/public_api_guard/components/datepicker.api.md
Labels: bug
